### ISSUE TITLE
Creating from source - jars have the wrong version

### ISSUE THREAD

**Issue by FireBurn** [lensesio/stream-reactor#1021]
https://github.com/lensesio/stream-reactor/blob/66bfd59f639ae07930fa5de61f85ebe7252b015e/project/Settings.scala#L36

Pretty sure this line needs updating, but I'm not overly familiar with sbt

Current jar name building from 6.0.1 tag:

kafka-connect-jms_2.13-5.1-SNAPSHOT.jar

**Comment by davidsloan** [comment]
You are absolutely right (even down to the line of code), I've raised a PR to fix this.
