### ISSUE TITLE
[Question] - kafka-connect-aws-s3 - SDK version?

### ISSUE THREAD

**Issue by yossisc** [lensesio/stream-reactor#1039]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
v0.2.5

Can someone please tell what is the SDK / Java/ version is using for the latest kafka-connect-aws-s3?

**Comment by davidsloan** [comment]
@yossisc current version builds with java 17, as this provides us the best balance between compatibility with Kafka connect and maturity of the libraries we rely on.

**Comment by davidsloan** [comment]
https://github.com/lensesio/stream-reactor/blob/91988ac14d13665ca9e3a0922e14a216315044d1/project/Dependencies.scala#L84

Currently 2.20.69.

But happy to accept a pull request updating this to a newer version, we try to keep it up-to-date.

**Comment by davidsloan** [comment]
The new version of the S3 connector, 6.2.0, available here:
https://github.com/lensesio/stream-reactor/releases/tag/6.2.0

upgrades this dependency to the latest, `2.25.6`
