### ISSUE TITLE
Kafka to HTTP Sink: Issue with setting the Content Type Header

### ISSUE THREAD

**Issue by zudiay** [lensesio/stream-reactor#1259]
# Issue Guidelines

Version Stream Reactor 7.2.0

 I want to send a PUT request through the sink to an endpoint. The request is being sent but i am not able to set the Content-Type in headers, so my request gets a 415 Unsupported Media type response. 

Here is my connector
```
{
    "name": "pause-http-sink-connector",
    "config": {
        "connector.class": "io.lenses.streamreactor.connect.http.sink.HttpSinkConnector",
        "connect.http.config": "{\"method\":\"Put\",\"endpoint\":\"http://localhost:8083/connectors/clickhouse-masterdata-sink-connector/pause\",\"content\":\"{}\",\"headers\":[[\"Content-Type\",\"application/json\"]],\"batch\":{\"batchCount\":1}}",
        "errorThreshold": "1",
        "tasks.max": "1",
        "topics": "clickhouse.masterdata_sync.dead_letter_queue",
        "name": "pause-http-sink-connector",
        "value.converter": "org.apache.kafka.connect.storage.StringConverter",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter"
    },
    "tasks": [
        {
            "connector": "pause-http-sink-connector",
            "task": 0
        }
    ],
    "type": "sink"
}
```

After i send a post request to my kafka-connect, i can see the connector is running and healthy

```
{
    "name": "pause-http-sink-connector",
    "connector": {
        "state": "RUNNING",
        "worker_id": "10.140.7.61:8083"
    },
    "tasks": [
        {
            "id": 0,
            "state": "RUNNING",
            "worker_id": "10.140.7.61:8083"
        }
    ],
    "type": "sink"
}
```

After the connectors execution, i am viewing in the sent request, the headers are empty and the content type is not correctly set. Could you please help?

I am referring to [docs](https://docs.lenses.io/5.5/connectors/sinks/httpsinkconnector/) for configuration

**Comment by davidsloan** [comment]
Hi there @zudiay

Thanks for the bug report!  I can confirm this is an issue for the initial release of the HTTP sink connector.

I have pushed a change to our master branch that will resolve this issue.

Are you able to build the code from master branch and check that the fix resolves your issue?

Thank you 🙏

**Comment by zudiay** [comment]
hi @davidsloan

Thank you for the quick response 🙌  I am seeing there are no updates in the releases, are you planning on making one including this commit?


Thanks

**Comment by davidsloan** [comment]
Yes, we will be, in about two weeks time - but first wanted to confirm this working with you pre-release.

**Comment by zudiay** [comment]
Oh I see,
I am using Dockerfile to install the connector. Previously I did

```
# Stage 0: Download the HTTP Sink Connector using an image with wget
FROM alpine:latest as downloader
RUN apk add --no-cache wget unzip
WORKDIR /downloads
RUN wget https://github.com/lensesio/stream-reactor/releases/download/7.2.0/kafka-connect-http-7.2.0.zip
RUN chmod 777 /downloads/kafka-connect-http-7.2.0.zip

# Use the existing Kafka Connect image as a base
FROM --platform=linux/amd64 confluentinc/cp-kafka-connect:latest

# Install unzip in the base image
USER root
RUN yum install -y unzip

# Install additional connectors as needed
RUN confluent-hub install --no-prompt confluentinc/connect-transforms:1.4.3

# Copy the downloaded Lenses.io Stream Reactor HTTP Sink Connector
COPY --from=downloader /downloads/kafka-connect-http-7.2.0.zip /tmp/
RUN unzip /tmp/kafka-connect-http-7.2.0.zip -d /usr/share/confluent-hub-components/

# Ensure necessary permissions are set
RUN chmod +x /etc/confluent/docker/run
ENTRYPOINT ["/etc/confluent/docker/run"]

```

I need to change this dockerfile and generate the jar file from the master zip. Can you help me with the configuration?

**Comment by zudiay** [comment]
I can verify the issue is resolved, thank you for your support. I am waiting for the release 🙏

**Comment by davidsloan** [comment]
[Release available today.](https://github.com/lensesio/stream-reactor/releases/tag/7.3.0)
