### ISSUE TITLE
S3 connector documentation about flush options is outdated

### ISSUE THREAD

**Issue by nojetlag** [lensesio/stream-reactor#1435]
https://docs.lenses.io/connectors/kafka-connectors/sink/aws-s3 states that one should use WITH_FLUSH_COUNT, WITH_FLUSH_SIZE, WITH_FLUSH_INTERVAL, however when creating a connector based on this documentation kafka connect complains that these should be now properties.

**Comment by stheppi** [comment]
Resolved.
