### ISSUE TITLE
Add ClickHouse sink

### ISSUE THREAD

**Issue by amq** [lensesio/stream-reactor#249]
[ClickHouse](https://clickhouse.yandex/) is comparable to InfluxDB, Druid and Vertica. It offers an SQL-like syntax and a very high performance.

Among others, it is used by [CloudFlare](https://blog.cloudflare.com/how-cloudflare-analyzes-1m-dns-queries-per-second/).

**Comment by andrewstevenson** [comment]
@amq we'll take a look. If you would like to sponsor the work it can always get it done quicker, drop me a direct mail if you want to know more.

**Comment by andrewstevenson** [comment]
Not in our roadmap and other available.
