### ISSUE TITLE
kafka-connect-bloomberg retry mechanism for disconnect

### ISSUE THREAD

**Issue by lwu08** [lensesio/stream-reactor#481]
In my case of using the connector, the connection with Bloomberg is unstable and can be disconnected at any time. To enhance the robustness, is there any retry mechanism for disconnected? If the current kafka-connect framework does not have related support, what should be the best practice to implement it by myself? Thanks!

**Comment by andrewstevenson** [comment]
@lwu08 Any reason for closing?

**Comment by andrewstevenson** [comment]
@lwu08 In the poll method you would have to check if the connection is still open, if not reconnect.

Contributions welcome!

**Comment by davidsloan** [comment]
I am closing this ticket as the Bloomberg connector has been deprecated and no longer part of the project.
