### ISSUE TITLE
Cassandra Connector DCAwareRoundRobinPolicy

### ISSUE THREAD

**Issue by abschwa** [lensesio/stream-reactor#539]
The Cassandra sink currently uses the DCAwareRoundRobinPolicy, but the builder is not configurable.  According to the load balancing docs for the Cassandra Driver 3.5 (https://docs.datastax.com/en/developer/java-driver/3.5/manual/load_balancing/), since no `withLocalDC` is given, it will by default use the first datacenter it connected to at initialization.  Giving a list of contact points that includes multiple DCs would then only connect to one DC at random, and distribute the load over only that single DC.

To fully support DCAwareRoundRobinPolicy, my suggestion would be to add some CassandraConfigConstants that would configure the policy builder.

**Comment by andrewstevenson** [comment]
@abschwa Fancy contributing a PR?

**Comment by abschwa** [comment]
Sure, I'll get started on it.

**Comment by andrewstevenson** [comment]
Fixed in #669
