### ISSUE TITLE
kafka-connect-ftp-1.2.1-2.1.0-all.jar: file content is sent in an unreadable way

### ISSUE THREAD

**Issue by fcolecumberri** [lensesio/stream-reactor#562]
# Issue Guidelines

this issue is about kafka-connect-ftp

Please review these questions before submitting any issue?

### What version of the Stream Rector are you reporting this issue for?
kafka-connect-ftp-1.2.1-2.1.0-all.jar

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
I think so, but I'm not sure. we are using Kafka 2.3.0-1.1.0

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?
http://docs.datamountaineer.com/en/latest/faq.html
doesn't lead to a FAQ page (at least not anymore, don't know if once it did)
I have consulted https://docs.lenses.io/connectors/faq.html

### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes, in this case it's https://docs.lenses.io/connectors/source/ftp.html

### What is the expected behaviour?
We introduce a file in a FTP server that contains text and then the connector downloads it and send the content through a topic.
For example lets say the file in this case content is:
{"sample": "sampletext", "Msg": "sample message"}
so I would expect to receive in the topic:
{"sample": "sampletext", "Msg": "sample message"}

### What was observed?
The content of the file was:
{"sample": "sampletext", "Msg": "sample message"}
but the topic received:
"eyJzYW1wbGUiOiAic2FtcGxldGV4dCIsICJNc2ciOiAic2FtcGxlIG1lc3NhZ2UifQ=="

### What is your connector properties configuration?
connector.class=com.eneco.trading.kafka.connect.ftp.source.FtpSourceConnector
errors.retry.timeout=0
errors.log.include.messages=false
ftp.max.backoff=PT30M
tasks.max=1
ftp.password=*********
errors.retry.delay.max.ms=60000
ftp.max.poll.records=10000
ftp.address=*********
ftp.file.maxage=P14D
ftp.refresh=PT1S
ftp.keystyle=struct
connect.ftp.sourcerecordconverter=com.datamountaineer.streamreactor.connect.ftp.source.NopSourceRecordConverter
connect.ftp.fileconverter=com.datamountaineer.streamreactor.connect.ftp.source.SimpleFileConverter
errors.tolerance=none
ftp.monitor.update=/test.json:test
config.action.reload=RESTART
errors.log.enable=false
ftp.user==*********

**Comment by andrewstevenson** [comment]
@fcolecumberri You are applying the NoSourceRecordConverter, so the file contents are getting passed through directly. Are you using avro?

**Comment by charalamm** [comment]
Hello, I am having the same issue with the difference I am using:
```
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```
and I am getting int he topic:
```
[B@229a12b9
[B@73668059
[B@1ca04be5
[B@24046322
[B@39ed8179
[B@2a7a554f
```

No I am not using Avro. Is there a way to avoid using Avro?

**Comment by fcolecumberri** [comment]
@davidsloan Sorry, I am no longer working on the project, I have no idea if that help would have worked, thanks and sorry.
