### ISSUE TITLE
How to add key to Kafka message with Binary converter

### ISSUE THREAD

**Issue by orbiran88** [lensesio/stream-reactor#581]
I'm using the MQTT Source connector with the following configuration:

```
connector.class=com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector
tasks.max=10
topics=mqtt.gw.ipfix
connect.mqtt.service.quality=2
connect.mqtt.converter.throw.on.error=false
connect.mqtt.hosts=tcp://vernemq-control:1883
key.converter.schemas.enable=false
value.converter.schemas.enable=false
connect.mqtt.connection.clean=false
connect.mqtt.kcql=INSERT INTO mqtt.gw.ipfix SELECT * FROM `$share/connect/gw_ipfix` WITHCONVERTER=`com.datamountaineer.streamreactor.connect.converters.source.BytesConverter`
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
```

I'm getting on Kafka the key: `Struct{topic=gw_ipfix,id=0}`

Can someone explain why I get this Key and how I can manipulate him? I need to change the key to a random string for splinting the messages to different topic partitions.. Thanks.

**Comment by orbiran88** [comment]
Looking at:
https://github.com/Landoop/stream-reactor/blob/c98b94c6941e2f13f42c8e02f0a1fe0be535043b/kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala#L90

We using here the `getId` from `MqttMessage` class, I wounder if we should add an option for override the Key string with a UUID string, what do you think? @stheppi ?

**Comment by orbiran88** [comment]
**UPDATE:**

For now I thinking of that its better to override the default key that comes from the Converter.
The reason for that is that no messageId came from the MQTT.. its always "0", I will add new option to the MQTT source connector to override the default key to a NULL, then Kafka can do the round-robin partition strategy.

```
/**
 * The default partitioning strategy:
 * <ul>
 * <li>If a partition is specified in the record, use it
 * <li>If no partition is specified but a key is present choose a partition based on a hash of the key
 * <li>If no partition or key is present choose a partition in a round-robin fashion
 */
```

**Comment by stheppi** [comment]
You can build your own converter. https://docs.lenses.io/connectors/source/mqtt.html#converters

This is the bytesConverter.
https://github.com/Landoop/kafka-connect-common/blob/8444b8d863ab724fe1d64948e1def3e5cf9036ce/src/main/scala/com/datamountaineer/streamreactor/connect/converters/source/BytesConverter.scala#L24

In your custom converter you can do whatever you need.

**Comment by orbiran88** [comment]
That's what I will do.. Thanks!

**Comment by andrewstevenson** [comment]
@orbiran88 Can we close this issue now?
