### ISSUE TITLE
Influxdb timestamp docs

### ISSUE THREAD

**Issue by WheresAlice** [lensesio/stream-reactor#596]
### What is the expected behaviour?

The documentation for the influxdb connector mentions nothing about the format for the timestamp field, and so we used seconds since epoch.

### What was observed?

All records were being inserted into Influxdb with a date in 1970.

Upon reading the source code for the connector it became apparent that the timestamp field should be in milliseconds since epoch.  The documentation should be updated to cover which types and formats are expected by the connector.

**Comment by andrewstevenson** [comment]
@WheresAlice thanks, we'll update the docs

**Comment by afausti** [comment]
Looking at the [source code ](https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/TimestampValueCoerce.scala) the assertion that timestamps should be in milliseconds is true if the connector is parsing `String` or `Date` types.  

I came across this issue when using the connector with Unix timestamps in seconds specified as `double` in the Avro schema - I got the following error:

```
java.lang.IllegalArgumentException: Invalid value for field:private_sndStamp.Value '1.3261721783120623E9' is not a valid field for the timestamp
    at com.datamountaineer.streamreactor.connect.influx.writers.TimestampValueCoerce$.apply(TimestampValueCoerce.scala:35)
    at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$buildPointFromStruct$2$$anonfun$19.apply(InfluxBatchPointsBuilder.scala:237) 
```

I would be happy to try a PR if you guys think it is reasonable to support this timestamp format as well.

**Comment by afausti** [comment]
See also #625

**Comment by andrewstevenson** [comment]
Docs updated and will be in the next release
