### ISSUE TITLE
Is Elastic 6 Sink connector v1.1.0-1.1.0 compatible with Kafka brokers 2.3?

### ISSUE THREAD

**Issue by alexmorosmarco** [lensesio/stream-reactor#624]
Hi, I am currently using the [kafka-connect-elastic6](https://docs.lenses.io/connectors/sink/elastic6.html) connector **v1.1.0-1.1.0** on a Kafka Connect cluster that works on top of an **Apache Kafka cluster v1.1**.

The download I am using is [kafka-connect-elastic6-1.1.0-1.1.0-all.tar.gz](https://github.com/Landoop/stream-reactor/releases/download/1.1.0/kafka-connect-elastic6-1.1.0-1.1.0-all.tar.gz).

_My question is:_
Is that same JAR compatible with a Kafka Connect cluster working on top of an **Apache Kafka cluster v2.3**?

My doubt comes from:
* I am evaluating upgrading Kafka & Kafka Connect clusters to `v2.3` and I want to clarify this first.
* In the past we tried to use the connector version `kafka-connect-elastic6-1.2.2-2.1.0-all.tar.gz` in our Kafka `v1.1` but didn't work despite in [the documentation](https://docs.lenses.io/connectors/sink/elastic6.html) it is written that a prerequisite is 
> Apache Kafka 0.11.x of above

Thanks so much.

**Comment by stheppi** [comment]
Hi @alexmorosmarco,
 Let's take each of your doubts one by one.

1. the Kafka Connect API has not been broken with Kafka 2.3. As you might know, the connectors are plugins to run within the Kafka Connect framework. If Kafka Connect would break the API all the connectors for it would be broken unless recompiled. That wouldn't be ideal to force each user + developer to take this road.

2. We do not know of any such problem. The description "but didn't work despite .."  begs the question: what problems did you encounter with it? We would really like to know what were the issue you faced. So we would appreciate if you could share some information or even join our community and talk with our engineers. 
https://launchpass.com/lensesio 

Which Connect distribution do you run?

**Comment by alexmorosmarco** [comment]
Hi @stheppi ,

I answer about the points:

Point 1) Thanks, so then I can use same JAR in a newer KC cluster on top of a Kafka cluster `v2.3`


Point 2) Sorry, I have realized that I wrote wrong that point. The problem was with the FTP connector. It could be thought it is not related but for me it is as I think you make a release of all connectors at the same time sure following the same versioning policy. Let me re-write it:
>In the past we tried to use the FTP connector JAR [kafka-connect-ftp-1.2.2-2.1.0](https://github.com/Landoop/stream-reactor/releases/download/1.2.2/kafka-connect-ftp-1.2.2-2.1.0-all.tar.gz), from [the official site](https://docs.lenses.io/2.3/connectors/source/ftp.html), in our Kafka `v1.1` but didn't work. There isn't any documentation present in that connector page regarding the Kafka compatibility.

It is time ago, I am not sure if we saw a clear exception related with the versioning. Then we tried with the version [kafka-connect-ftp-1.1.0-1.1.0](https://github.com/Landoop/stream-reactor/releases/download/1.1.0/kafka-connect-ftp-1.1.0-1.1.0-all.tar.gz) and did work. I assume the suffix of the release files is the version of the Kafka cluster compatibility. By that experience I understand that a JAR is not, or may not, be compatible with an older Kafka cluster. Is this right?

Could you add to the connector documentation or maybe to a global connectors documentation, how is the compatibility between the connectors and Kafka Connect and Kafka clusters?

**Comment by davidsloan** [comment]
Kafka Compatibility is listed here in the documentation:
https://docs.lenses.io/4.3/integrations/connectors/stream-reactor/install/#kafka-compatibility

We have just released 3.0.0 of the connectors.  If you give it a try, please report any further problems you experience.

I hope you don't mind if i close this ticket as it is old and I do not think there is any action outstanding.  Please let me know if I am incorrect!
