### ISSUE TITLE
Cassandra Sink Connector - Exception in thread "main" java.lang.InstantiationError: com.typesafe.scalalogging.Logger 

### ISSUE THREAD

**Issue by bcashier** [lensesio/stream-reactor#630]
Hi,

I downloaded Cassandra Sink Connector from:
https://docs.lenses.io/connectors/sink/cassandra.html

And added to Kafka "libs/" folder, and then when i try to launch the kafka server:
`./kafka-server-start.sh ../config/server.properties`

I am getting this error message:

```
Exception in thread "main" java.lang.InstantiationError: com.typesafe.scalalogging.Logger
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:48)
	at kafka.utils.Log4jControllerRegistration$.<init>(Logging.scala:25)
	at kafka.utils.Log4jControllerRegistration$.<clinit>(Logging.scala)
	at kafka.utils.Logging.$init$(Logging.scala:47)
	at kafka.Kafka$.<init>(Kafka.scala:30)
	at kafka.Kafka$.<clinit>(Kafka.scala)
	at kafka.Kafka.main(Kafka.scala)

```

Is there a way to solve this error please ?

Thanks

**Comment by stheppi** [comment]
Thanks for reaching out.

I know Kafka is hard, it requires quite some learning, and it's easy to make a rookie mistake. Unfortunately you are trying to start the Kafka broker thinking you start Kafka connect. The name it's in the shell script. Kafka-server-start. 

You have missed installing the connector section: https://docs.lenses.io/connectors/sink/cassandra.html#installing-the-connector and what you did you copied the jar in the Kafka libs folder. That is a big no no. Please follow the steps provided there to install the connector. 

We have an easier and better solution for you. It will save you time. 
We have Lenses Box the one place for trying our connectors when Kafka knowledge is limited. https://lenses.io/box/ It's free it has the connector installed. It's just a docker command away.

**Comment by bcashier** [comment]
@stheppi Thank you for your answer !

I want to use the standard Kafka version downloaded from Apache website only, is it possible without third party program please ?

`etc/schema-registry ` is not present in the standard version.

Notice that I have to start the Kafka server first in order to use Connect-Standalone.

Your help will be appreciated.

**Comment by stheppi** [comment]
Lenses Box uses the default Kafka distribution. And it's one docker image which starts everything for you Zookeeper, Kafka Brokers, Kafka Connect. 

If you want to deploy and configure everything yourself you can do that of course. With a bit of google and reading you can do that yourself: 

To start the Kafka brokers:
  https://kafka.apache.org/documentation/#quickstart_startserver

To start  Kafka  Connect: 
  https://kafka.apache.org/documentation/#connect 

Just follow the instruction.More than this I am afraid i cannot do. Just  follow the steps ad-litteram

**Comment by bcashier** [comment]
@stheppi Starting the broker and Connect is already done.

The problem is when using cassandra-sink-connector JAR file inside libs/ folder that I receive that error message.

I even used an external folder using plugin.lib option, this giving the same error aswell.

**Comment by stheppi** [comment]
I will re-share with you the docs for installing the connection (It has nothing to do with vanilla kafka or not): https://docs.lenses.io/connectors/sink/cassandra.html#installing-the-connector

The docs tell you where to copy the jar and they give you the example of running Connect in distributed mode.  To configure the worker it points to `etc/schema-registry/connect-avro-distributed.properties`. Kafka connect standlone needs a configuration file as well, which I assume you already pass because otherwise it just does not start. Here is the docs for running Connect with the Cassandra Sink enabled:
```Install and configure a Kafka Connect cluster
1.Create a folder on each server called plugins/lib
2.Copy into the above folder the required connector jars from the stream reactor download
3. Edit connect-avro-distributed.properties in the etc/schema-registry folder and uncomment the plugin.path option. Set it to the root directory i.e. plugins you deployed the stream reactor connector jars in step 2.
4.Start Connect, bin/connect-distributed etc/schema-registry/connect-avro-distributed.properties```

Also, maybe you missed my earlier message, but let me repeat it again:
``` do not to copy the jar into the `libs/` folder. That is the folder which contains all the Kafka broker Jar artefacts. A connector can easily overwrite some files.
```

Use the plugins/lib or any other folder on your machine. The set the `plugin.path` in your Kafka connect standalone properties file.

**Comment by bcashier** [comment]
@stheppi You hadn't to bother yourself to past again the same messages.

It seem that there misunderstanding related to my question but it doesn't matter, I just found about another customizable option ...

Thanks for your time.
