### ISSUE TITLE
Upsert to a specific document using kafka connect sink to elasticsearch

### ISSUE THREAD

**Issue by KabDeveloper** [lensesio/stream-reactor#634]
Hi,

I am using kafka-connect-elastic6, I want to know how I can `UPSERT` datas received from the topic.

Datas are like this;
`{"1574922337":[{"price": 1, "product": 2], "1574922338":[{"price": 13, "product": 5}], "1574922339":[{"price": 0.2, "product": 1}]}`

I want from the kafka connector to parse this JSON event message received from the topic in order to create 3 documents at a time with `id=TIMESTAMP`, and this using `UPSERT` (If id already exists, we update it only, if not exists it will be added).

Do this kafka connector can handle this type of requests please ?

Waiting your help please.

**Comment by andrewstevenson** [comment]
@bcashier the connector supports KCQL that allows you to select which fields you want to insert into the document and also choosing which fields are the primary key. You payload looks like json without a schema. https://docs.lenses.io/connectors/sink/elastic6.html#kcql-support

**Comment by davidsloan** [comment]
@KabDeveloper do you still have an issue outstanding or can this be closed?
