### ISSUE TITLE
CassandraJsonWriter does not log the table name for InvalidQueryException

### ISSUE THREAD

**Issue by sachinteotia30** [lensesio/stream-reactor#636]
# Issue Guidelines

ERROR Encountered error JSON values map contains unrecognized column: XXX (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:62)

Please review these questions before submitting any issue?

### What is the expected behaviour?
CassandraJsonWriter should log the table name whenever InvalidQueryException is encountered

**Comment by davidsloan** [comment]
This has been fixed and will be included in the next release.
