### ISSUE TITLE
Mqtt Source :  Dynamic Target kafka topic selection

### ISSUE THREAD

**Issue by DrAyoub** [lensesio/stream-reactor#639]
Hi,
I'm trying to use MQTT Source connector. My use case is to read a message from the Mqtt topic and publish it on a specific kafka topic depending on the message content.

I used the following KCQL but does not work:
_connect.mqtt.kcql=INSERT INTO `$datastreamType` SELECT * FROM /Observations WITHTARGET = datastreamType_

**Example of functioning desired :**
mqtt topic : _"/Observations"_
payload : 
_{
    "phenomenonTime" : "2019-11-28T16:45:57.597Z",
    "resultTime" : "2019-11-28T16:45:57.000Z",
    "result" : "Closed",
    "@iot.id" : "8d2ad2f6-11fe-11ea-b9c8-57ed631caa60",
    "datastreamType" : "doorPosition",
    "truckId" : "7971d710-2b0d-4e50-b0f1-2dd74758781d",
    "fleetId" : "806d5f55-8878-4fe3-ba06-78b466ce188a"
}_
==>  kafka topic : _"doorPosition"_

**Does MQTT Source support that ??**

**Comment by andrewstevenson** [comment]
@DrAyoub  Have you read https://docs.lenses.io/connectors/source/mqtt.html ?

you need 

`insert into doorPosition select * from /Observations`

**Comment by DrAyoub** [comment]
Thank you @andrewstevenson for your quick reply,
Yes, I have read the docs of MQTT Source.

In your response _insert into doorPosition select * from /Observations_, the kafka topic was static. Is it possible to make it dynamic like the MQTT topic in [MQTT Sink](https://docs.lenses.io/connectors/sink/mqtt.html#kcql-support) (Examples Dynamic target selection).

**Comment by andrewstevenson** [comment]
@DrAyoub At present no, contributions welcome!

**Comment by andrewstevenson** [comment]
@DrAyoub Resolved in #650
