### ISSUE TITLE
RabbitMQ Connector doesn't configure client to use virtual host

### ISSUE THREAD

**Issue by cheplv** [lensesio/stream-reactor#651]
RabbitMQ Connector always connects to "/" virtual host without setup of configuration
https://github.com/lensesio/stream-reactor/blob/66ad3eb172c901bed84e152b76930853b1f1cfe4/kafka-connect-rabbitmq/src/main/scala/com/datamountaineer/streamreactor/connect/rabbitmq/client/RabbitMQClient.scala#L27

Will provide PR

**Comment by andrewstevenson** [comment]
@cheplv Thanks. We don't official support the RabbitMQ sink since the JMS connector covers this but can you also check to see if the same fix can be applied there?

**Comment by cheplv** [comment]
@andrewstevenson can you point me to JMS AMQP integration with kafka-connect?

**Comment by cheplv** [comment]
I'll add more commits due there is need to substract "/" for virtualhost

**Comment by cheplv** [comment]
@andrewstevenson Now that changes works like a charm - hope this will be a good change ))
