### ISSUE TITLE
Elastic6 Sink not follows connect.elastic.retry.interval property

### ISSUE THREAD

**Issue by aromanos** [lensesio/stream-reactor#653]
When the sink is set to use the RETRY error policy, retries happen following the default interval of 60000 ms and not the configured value of 300000 ms.

Tested with:
        "connect.elastic.error.policy": "RETRY",
        "connect.elastic.max.retries": "5",
        "connect.elastic.retry.interval": "300000",

Versions:

Kafka distribution. lensesio/fast-data-dev:2.3.1
Landoop ElasticSink by Andrew Stevenson 1.2.1 (com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkTask:41)
StreamReactor-Version:       1.2.1
Kafka-Version:               2.1.0
Git-Repo:                    
Git-Commit-Hash:             79b697a6da2e5c4c5726bbf050d022433104b9f9
Git-Tag:                     1.2.4
StreamReactor-Docs:          https://docs.lenses.io/connectors/

Thanks in advance!

**Comment by andrewstevenson** [comment]
@aromanos #654 fixes this. Thanks for reporting!
