### ISSUE TITLE
Connect SQL engine does not support Avro aliases

### ISSUE THREAD

**Issue by afausti** [lensesio/stream-reactor#656]
### What version of the Stream Reactor are you reporting this issue for?
1.2.3

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes, I'm running the InfluxDB Sink connector with Kafka Connect 5.3.1

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Yes, I'm running InfluxDB 1.7

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes, both https://docs.lenses.io/connectors/sink/influx.html#kcql-support  and https://docs.lenses.io/sql/connectSql.html

### What is the expected behaviour?
I'm using the InfluxDB sink connector with a KCQL query to specify the field which should be used as the InfluxDB timestamp, ``private_sndStamp`` in my example:

```
INSERT INTO mytopic SELECT * FROM mytopic WITHTIMESTAMP private_sndStamp
```

The messages are sent as Avro and the corresponding Avro schemas are registered in the schema registry.

Avro supports [aliases](https://avro.apache.org/docs/1.8.1/spec.html#Aliases), which would be useful in my use case to facilitate schema evolution.

So, in the Avro schema, I tried this mapping:

```
...
{"name":"private_sndStamp","type":"double","aliases":["private_efdStamp"]}
...
```

and used the alias name in my KCQL like this:

```
INSERT INTO mytopic SELECT * FROM mytopic WITHTIMESTAMP private_efdStamp
```

### What was observed?

I got the following error suggesting that KCSQL does not support aliases:

```
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Couldn't find field 'private_efdStamp' in the schema:private_kafkaStamp,ScriptQueueID,private_revCode,private_sndStamp,private_rcvStamp,private_seqNum,private_origin,private_host,heartbeat,priority
```

**Comment by andrewstevenson** [comment]
@afausti Unfortunatley the AvroConverter for connect, from Confluent, doesn't pass through the Avro aliases to the Connect Struct format, therefore we don't have the information to be able to check. So this is not possible.
