### ISSUE TITLE
Lenses kudu sink connector auto create option creates a kudu table with a binary data type column but unable to create external table from impala.

### ISSUE THREAD

**Issue by mohanrajank** [lensesio/stream-reactor#657]
Hi,
     I am trying to push the below data to my kudu table with **auto-create** option it creates the table in kudu with a binary column, but impala doesn't support the external table creation with a binary data type. there is a way to overcome this?

1. Topic data

{
"Id": 39,
"Msg": "sampletest36",
"Created_At": 1577445800487
}

2. Sink config 

{
"name": "snk_test",
"config": {
"connector.class": "com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector",
"topics": "mssql.dbo.date_test",
"connect.kudu.schema.registry.url": "http://localhost:8081",
"connect.kudu.master": "kudumaster:7051",
"connect.kudu.kcql": "insert into impala::default.date_test select * from mssql.dbo.date_test AUTOCREATE DISTRIBUTEBY Id INTO 3 BUCKETS AUTOEVOLVE"
}
}

**Comment by andrewstevenson** [comment]
@mohanrajank as discussed you can use a transformer to convert binary data to something Impala can handle.
