### ISSUE TITLE
MQTT-connector Scala module 2.9.10 requires Jackson Databind version >= 2.9.0 and < 2.10.

### ISSUE THREAD

**Issue by alvistar** [lensesio/stream-reactor#685]
Hello,
trying to use mqtt-connector with Confluent community 5.4.1

While mqtt-source works correctly, I receive this error starting the connector:

MQTT-connector Scala module 2.9.10 requires Jackson Databind version >= 2.9.0 and < 2.10.

I saw a similar issue, now closed, on https://github.com/lensesio/stream-reactor/issues/637 and I do suspect they are related.

Thanks

**Comment by andrewstevenson** [comment]
@alvistar how are you adding the connector to the cluster? @ulfox

**Comment by alvistar** [comment]
Hi, just placing in plugins folder

plugin.path=/usr/share/java,/opt/stream-reactor

Downgrading to confluent-5.3.3 I am able to use it.

Thanks,
a.

**Comment by ulfox** [comment]
Trying to reproduce this

**Comment by ulfox** [comment]
I can confirm that installing mqtt 2.0 in plugin.path with confluent connect 5.4.1 yields the reported error

**Comment by andrewstevenson** [comment]
@alvistar Kafka 2.4 moved to Scala 2.12. so we upgraded the Stream reactor, however, Confluent, with 5.4 (Kafka 2.4) remained on Jackson 2.9. 

We have tested the SR 1.2.7 works on Kafka 2.4 on our side so we recommend you use that version for Kafka versions upto and including 2.4.  Can you confirm this in your environment?

For Kafka 2.5 move to SR 2.0+.

We'll do a 2.0.1 release to bring the jar names aligned.

**Comment by alvistar** [comment]
Him
thanks for the quick reply.

At the moment I don't have a production environment, so I can easily switch to another version.
I will try to use Kafka 2.5, but I am happy staying also with Confluent 5.3.3 at the moment for developing.
