### ISSUE TITLE
Possibility to read message properties in (JMS) source connector converters

### ISSUE THREAD

**Issue by AdiWehrli** [lensesio/stream-reactor#691]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
2.0.0-2.4.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
yes (2.5.0, 5.5.0)

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
yes

### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes

### What is the expected behaviour?
In source connectors the ```com.datamountaineer.streamreactor.connect.converters.source.Converter``` trait should also provide a possibility to pass additionally (JMS) message properties. As the message is not passed to the converter, we could not read any property except we would patch the Converter trait ourselves.

### What was observed?
We cannot get (JMS) message properties within the mentioned trait method.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
not applicable

### What is your connector properties configuration (my-connector.properties)?
not applicable

### Please provide full log files (redact and sensitive information)
Current:
`trait Converter {
  def initialize(map: Map[String, String]): Unit = {}
  def convert(kafkaTopic: String, sourceTopic: String, messageId: String, bytes: Array[Byte], keys:Seq[String] = Seq.empty, keyDelimiter:String = "."): SourceRecord
}`

Requested:
`trait Converter {
  def initialize(map: Map[String, String]): Unit = {}
  def convert(kafkaTopic: String, sourceTopic: String, messageId: String, bytes: Array[Byte], properties: Map[String, String] = Map.empty[String, String], keys:Seq[String] = Seq.empty, keyDelimiter:String = "."): SourceRecord
}`

Thanks very much and best regards

**Comment by andrewstevenson** [comment]
@AdiWehrli release in kafka-connect-common 2.0.4

trait Converter {
  def initialize(map: Map[String, String]): Unit = {}

  def convert(kafkaTopic: String,
              sourceTopic: String,
              messageId: String,
              bytes: Array[Byte],
              keys: Seq[String] = Seq.empty,
              keyDelimiter: String = ".",
              properties: Map[String, String] = Map.empty): SourceRecord
}
