### ISSUE TITLE
Can we get a 2.1.0 release?

### ISSUE THREAD

**Issue by nenad** [lensesio/stream-reactor#697]
Hey team, thanks for doing a great job maintaining these connectors :+1: 

Is there a plan to build and publish a release for 2.1.0? 

There is a crucial change coming in from kafka-connect-common which has been merged in 2.1.0 tag that our team needs. Since we are using a third-party hosted solution for Kafka Connect which uses your connectors we cannot simply build and use it ourselves.

I'd really appreciate your response!
Cheers,
Nenad

**Comment by andrewstevenson** [comment]
@nenad Done
