### ISSUE TITLE
How to stream any Cassandra table with the Connector

### ISSUE THREAD

**Issue by rveve** [lensesio/stream-reactor#708]
Hi All, Do we have a good channel to ask this question instead making it an issue.
I have a regular table in cassandra, no TIMESTAMP or TIME related field, so cannot use the Incremental mode
to publish the Data to a Kafka topic, so I decided to use the bulk mode, the data gets published
to the topic, but the entries are repeated 100 times until I pause the connector.

is there a way to load this Data to the topic without repeating or reloading it over and over, any suggestion is welcome.

Thank you.

**Comment by andrewstevenson** [comment]
@rveve you need a column so the connector can track so unless you have this it won't work. Closing this ticket, contributions are welcome if you have an idea.
