### ISSUE TITLE
Cassandra sink connector failing :  A KCQL error occurred.Can't flatten from schema:Schema{ARRAY} by selecting 'field name''

### ISSUE THREAD

**Issue by neerajk22** [lensesio/stream-reactor#724]
Getting error - 

Caused by: java.lang.IllegalArgumentException: A KCQL error occurred.Can't flatten from schema:Schema{ARRAY} by selecting 'products'

Using Avro schemas.

sample Json -
"my_enterprise_id": "54321",
"application_id": "00123",
"system_code": "test code",
"products": [{
"product_codes": "PRD_0001",
"product_name": "my product",
"product_classification": "hello world"
}],

**Comment by andrewstevenson** [comment]
@neerajk22 flattening of arrays is not supported.
