### ISSUE TITLE
Cannot start producer console with the kafka-connect-influxdb-2.1.3-2.5.0-all.jar

### ISSUE THREAD

**Issue by xuzikun2003** [lensesio/stream-reactor#725]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
The latest version 2.13.

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes, I am running with Kafka-2.13

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
No

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is the expected behaviour?
I should be able to start kafka consumer console when I copy the stream-reactor jar to the kafka folder /opt/kafka/libs/

### What was observed?
After I copy the stream-reactor Kafka influxDB connector jar to Kafka jar folder
 cp influxdb_connector/kafka-connect-influxdb-2.1.3-2.5.0-all.jar /opt/kafka/libs/
Then I am not able to start the producer console, and I am getting the following error

agent@kafka-0:~$ /opt/kafka/bin/kafka-console-producer.sh  --topic test --bootstrap-server kafka-0.kafka-svc.test.svc.cluster.local:9092 --producer.config client.config
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/kafka/libs/kafka-connect-influxdb-2.1.3-2.5.0-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/kafka/libs/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.wrapRefArray([Ljava/lang/Object;)Lscala/collection/immutable/ArraySeq;
        at kafka.tools.ConsoleProducer$ProducerConfig.<init>(ConsoleProducer.scala:230)
        at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:41)
        at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
        
If I remove the Kafka influxdb connector jar from the kafka jar folder
  sudo rm /opt/kafka/libs/kafka-connect-influxdb-2.1.3-2.5.0-all.jar
then the producer console can run correctly.

**Comment by Antwnis** [comment]
@xuzikun2003 you copied the JAR under the kafka folder, whereas you need to add it to "Kafka Connect" ie. see https://docs.lenses.io/4.1/integrations/connectors/stream-reactor/install/ how to setup the **plugin.path**

**Comment by xuzikun2003** [comment]
Thanks for your hint. By specifying the plugin.path, I don't need to copy the jar to the Kafka folder and thus we can avoid the JAR conflict.  That works for me. I would like to close this issue now.
