### ISSUE TITLE
MQTT Connector: A KCQL error occurred. Can't select an element from an array(schema:Schema{myaddress:STRUCT})

### ISSUE THREAD

**Issue by ntnhan94** [lensesio/stream-reactor#740]
I am using: kafka-connect-mqtt-2.1.3-2.5.0-all.tar.gz
And confluent version: confluentinc/cp-kafka-connect-base:6.0.0

The mqtt connector throws the error attached when I use nested avro schema. Here is my schema:

        {
           "type":"record",
           "name":"myrecord",
           "fields":[
              {
                 "name":"id",
                 "type":"int"
              },
              {
                 "name":"name",
                 "type":"string"
              },
              {
                 "name":"address",
                 "type":{
                    "type": "record",
                    "name": "myaddress",
                    "fields":[
                       {
                          "name":"province",
                          "type":"string"
                       },
                       {
                          "name":"city",
                          "type":"string"
                       }
                    ]
                 }
              }
           ]
        }

Here is my connector config:

    name=mqtt
    connector.class=com.datamountaineer.streamreactor.connect.mqtt.sink.MqttSinkConnector
    tasks.max=1  
    topics=customers
    connect.mqtt.hosts=tcp://mqtt:1883
    connect.mqtt.clean=true 
    connect.mqtt.timeout=1000 
    connect.mqtt.keep.alive=1000 
    connect.mqtt.service.quality=1 
    connect.mqtt.client.id=dm_sink_id
    connect.mqtt.kcql=INSERT INTO /lenses/customers SELECT * FROM customers

I followed the guideline here: https://docs.lenses.io/4.1/integrations/connectors/stream-reactor/sinks/mqttsinkconnector/

[avro_nested_error_stacktrace.txt](https://github.com/lensesio/stream-reactor/files/5908340/avro_nested_error_stacktrace.txt)

**Comment by andrewstevenson** [comment]
@ntnhan94 unfortunately selecting elements from arrays in KCQL is not possible
