### ISSUE TITLE
Error: Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient

### ISSUE THREAD

**Issue by juergenhemelt** [lensesio/stream-reactor#750]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
2.1.3

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Kafka 2.6

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Hive 3.1.0.3.1.5.134-3

### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes

### What is the expected behaviour?
working Hive connector

### What was observed?
exception in logfile:

Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient with cause
class [Ljava.lang.Object; cannot be cast to class [Ljava.net.URI; ([Ljava.lang.Object; and [Ljava.net.URI; are in module java.base of loader 'bootstrap')

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
not relevant

### What is your connector properties configuration (my-connector.properties)?
see above

### Please provide full log files (redact and sensitive information)
see above

### Suggested Fix:
I run the Connect Cluster in a Java 11 JVM. Obviously the problem stems from this issue: https://issues.apache.org/jira/browse/HIVE-22190
Updating the Hive dependeny in build.gradle to at least 2.3.7 fixes the problem.

**Comment by davidsloan** [comment]
#852 seeks to upgrade the Hive Dependency to 3.1.3 and should also resolve this issue.  I'll leave it open until we've had a chance to verify it.

**Comment by davidsloan** [comment]
Closing as this was fixed some time ago.  Please let me know if you experience any further problems.
