### ISSUE TITLE
Race condition in StructFieldsExtractorBytes

### ISSUE THREAD

**Issue by vLukas-dev** [lensesio/stream-reactor#753]
stream-reactor 2.0.1

[StructFieldsExtractorBytes.scala](https://github.com/lensesio/stream-reactor/blob/467626660f6be4f3aa49c79e4818b2f66e8e569f/kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorBytes.scala#L99) contains a companion object (stateful singleton!) `StructFieldsExtractorBytes` with values `DateFormat` and `TimeFormat`, both instances of `java.text.SimpleDateFormat` - which is not synchronised.

Thus, launching more than one HBase sink connector in a single instance of kafka-connect is unsafe and crashes in the best case, writes corrupted data in the worst.

**Comment by davidsloan** [comment]
Thanks for the report.  I think the way forward here would be to replace SimpleDateFormat with DateTimeFormatter.

**Comment by davidsloan** [comment]
This has been fixed and will be included in the next release.
