### ISSUE TITLE
Error in documentation for LIMIT in KCQL

### ISSUE THREAD

**Issue by Ozsie** [lensesio/stream-reactor#756]
# Issue Guidelines

### What version of the Stream Reactor are you reporting this issue for?
4.1

This is not really an issue with Stream Reactor as such, but with the documentation.

At [the KCQL Support section](https://docs.lenses.io/4.1/integrations/connectors/stream-reactor/sources/s3sourceconnector/#kcql-support) of the documentation for Stream Reactor 4.1, the following line can be found

`INSERT INTO topicA SELECT * FROM testS3Bucket:pathToWriteTo STOREAS 'AVRO' LIMIT = 5000`

The correct syntax for LIMIT should be without =, as below.

`INSERT INTO topicA SELECT * FROM testS3Bucket:pathToWriteTo STOREAS 'AVRO' LIMIT 5000`

**Comment by andrewstevenson** [comment]
@davidsloan

**Comment by johnathana** [comment]
@Ozsie Thank you for your report. We updated the documentation.
