### ISSUE TITLE
Hive: Unable to change auto.offset.reset value for hive-sink connector consumer

### ISSUE THREAD

**Issue by anshme** [lensesio/stream-reactor#798]
I need to change consumer proprties in kafka connect, specifically consumer group id and auto.offset.reset. Able to change the group id but auto.offset.reset is not changing and takes the default value. I have provided the auto.offset.reset value in connector.properties, kafka-connect.properties and through the curl request as well. So clarification on which config goes in which config file would help a lot.

### What version of the Stream Reactor are you reporting this issue for?
1.2.7
### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes
### What is the expected behaviour?
The connector properties such as auto.offset.reset should change from default(earliest) to set value(latest).

### What was observed?
group.id changes to the specific name as mentioned in kafka-connect.properties, but auto.offset.reset is not changing from the same config file kafka-connect.properties.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
Kafka is running on the host system, hive is in remote server, kafka connect is in same machine that is running kafka but in a docker container.

### What is your connector properties configuration (my-connector.properties)?
kafka-connect.properties
`connect.hive.kcql=INSERT INTO orders_1 SELECT * FROM prod AUTOCREATE WITH_FLUSH_INTERVAL = 10
connect.hive.database.name=adhoc
connect.hive.metastore=thrift
auto.offset.reset=latest
connect.hive.metastore.uris=thrift://abc.org.in:9083
connect.hive.fs.defaultFS=hdfs://digital
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
group.id=hive_test
value.converter.schemas.enable=false
offset.storage.topic=_connect-offsets
config.storage.topic=_connect-configs
status.storage.topic=_connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
bootstrap.servers=http://localhost:9092
heartbeat.interval.ms=5000
enable.auto.commit=true
connect.hive.conf.dir=/etc/hadoop
connect.hive.hdfs.conf.dir=/etc/hadoop
plugin.path=/usr/share/java,/opt/lenses/lib,/data/kafka-connect
`

connector.properties
`name=local-file-sink
connector.class=com.landoop.streamreactor.connect.hive.sink.HiveSinkConnector
tasks.max=1
topics=prod
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter`

curl command - 
curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
 "name": "hive-sink",
 "config": {
    "name" : "hive-sink",
    "auto.offset.reset": "latest",
    "connector.class": "com.landoop.streamreactor.connect.hive.sink.HiveSinkConnector",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": false,
    "value.converter":"org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "key.ignore": "true",
    "schema.ignore": "true",
    "errors.tolerance": "all",
    "errors.log.enable":true,
    "errors.deadletterqueue.topic.name":"error_data",
    "errors.deadletterqueue.topic.replication.factor": 1,
    "behavior.on.malformed.documents": "ignore",
    "tasks.max": 1,
    "group.id": "hive_test",
    "topics": "upiprod",
    "connect.hive.kcql": "INSERT INTO orders_1 SELECT * FROM prod AUTOCREATE WITH_FLUSH_INTERVAL = 10",
    "connect.hive.database.name": "adhoc",
    "connect.hive.metastore": "thrift",
    "connect.hive.metastore.uris": "thrift://abc.org.in:9083",
    "connect.hive.fs.defaultFS": "hdfs://digital",
    "connect.hive.hdfs.conf.dir": "/etc/hadoop",
    "connect.hive.conf.dir": "/etc/hadoop"
 }
}'

### Please provide full log files (redact and sensitive information)
INFO ConsumerConfig values:
auto.commit.interval.ms = 5000
auto.offset.reset = earliest
bootstrap.servers = [http://localhost:9092]
check.crcs = true
client.dns.lookup = default
client.id =
connections.max.idle.ms = 540000
default.api.timeout.ms = 60000
enable.auto.commit = false
exclude.internal.topics = true
fetch.max.bytes = 52428800
fetch.max.wait.ms = 500
fetch.min.bytes = 1
group.id = hive_test
heartbeat.interval.ms = 5000
interceptor.classes = []
internal.leave.group.on.close = true
isolation.level = read_uncommitted
key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
max.partition.fetch.bytes = 1048576
max.poll.interval.ms = 300000
max.poll.records = 500
metadata.max.age.ms = 300000
metric.reporters = []
metrics.num.samples = 2
metrics.recording.level = INFO
metrics.sample.window.ms = 30000
partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
receive.buffer.bytes = 65536
reconnect.backoff.max.ms = 1000
reconnect.backoff.ms = 50
request.timeout.ms = 30000
retry.backoff.ms = 100
sasl.client.callback.handler.class = null
sasl.jaas.config = null
sasl.kerberos.kinit.cmd = /usr/bin/kinit
sasl.kerberos.min.time.before.relogin = 60000
sasl.kerberos.service.name = null
sasl.kerberos.ticket.renew.jitter = 0.05
sasl.kerberos.ticket.renew.window.factor = 0.8
sasl.login.callback.handler.class = null
sasl.login.class = null
sasl.login.refresh.buffer.seconds = 300
sasl.login.refresh.min.period.seconds = 60
sasl.login.refresh.window.factor = 0.8
sasl.login.refresh.window.jitter = 0.05
sasl.mechanism = GSSAPI
security.protocol = PLAINTEXT
send.buffer.bytes = 131072
session.timeout.ms = 10000
ssl.cipher.suites = null
ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
ssl.endpoint.identification.algorithm = https
ssl.key.password = null
ssl.keymanager.algorithm = SunX509
ssl.keystore.location = null
ssl.keystore.password = null
ssl.keystore.type = JKS
ssl.protocol = TLS
ssl.provider = null
ssl.secure.random.implementation = null
ssl.trustmanager.algorithm = PKIX
ssl.truststore.location = null
ssl.truststore.password = null
ssl.truststore.type = JKS
value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

**Comment by davidsloan** [comment]
Closing due to deprecation of the hive connector.
