### ISSUE TITLE
AWS S3 Connector as standalone installation

### ISSUE THREAD

**Issue by dmarupov** [lensesio/stream-reactor#800]
I am attempting to install/configure AWS S3 Connector to work with my vanilla Kafka Connect in Linux VM. Is it possible?

What I have tried so far:
I have downloaded and extracted: 'kafka-connect-aws-s3-2.1.3-2.5.0-all.tar.gz' in my Linux VM.

Result:
What I get is 'kafka-connect-aws-s3-2.1.3-2.5.0-all.jar'

I have further extracted this jar file and it looks like lots of folders and files that is confusing me.

Am I doing right? Is there a documentation on how to install/configure AWS S3 Connector on Kafka/Linux?

I appreciate any help/guidance I can get. Thank you in advance.

**Comment by davidsloan** [comment]
Hi @dmarupov .

The connectors aren't designed to be used standalone.  It is designed to be used as a connector plugin for Kafka Connect.

Please see our documentation for more details

https://docs.lenses.io/4.1/integrations/connectors/stream-reactor/install/
https://docs.lenses.io/4.1/integrations/connectors/stream-reactor/sinks/s3sinkconnector/

Let me know if you need any more help.
