### ISSUE TITLE
S3 connector build error

### ISSUE THREAD

**Issue by rae89** [lensesio/stream-reactor#804]
I am trying to build the kafka-connect-aws-s3 connector from the tag v.0.2.5, and get the following error:

`gradle :kafka-connect-aws-s3:shadowJar
`

> Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/respinoza/Projects/stream-reactor/build.gradle' line: 48
> 
> * What went wrong:
> A problem occurred evaluating root project 'stream-reactor'.
> > Plugin with id 'maven' not found.
> 
> 

Any idea on how to resolve this issue?

**Comment by davidsloan** [comment]
Unfortunately this project currently relies on an fairly old version of gradle.  Using a newer version will result in the issue you have seen.

Please use the gradle wrapper `gradlew` which is bundled inside the project, which should select the appropriate version of gradle for you to use.

**Comment by rae89** [comment]
@davebassan thank you for your reply.  Does the connector require a specific version of java? I ran the following command and got this error:

`./gradlew :kafka-connect-aws-s3:shadowJar`

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.11'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by davidsloan** [comment]
I am not @davebassan sorry, but I will try to help.

We run the build with Java 8 because of one of the legacy modules.

**Comment by rae89** [comment]
@davidsloan oops apologies for the wrong name.  And thank you for the quick reply, I was able to get the build to successfully run using Java 8.  

I have a followup question, where should I be expecting to find the jar files that have been built?  I am new to Kafka and have my cluster running on AWS MSK, and im trying to deploy the S3 connector on the hosted AWS MSK connector service.

**Comment by davidsloan** [comment]
@rae89 we have a releases page on 
https://github.com/lensesio/stream-reactor/releases
where the jars are already built so you don't have to.

And we are preparing the new release.

But if you really want to build it yourself.

Then after you have run shadowJar you can find the *-all.jar in 
/kafka-connect-aws-s3/build/libs
