### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by politrons** [lensesio/stream-reactor#805]
Hi all,  a couple weeks ago we made a contribution to Stream-reactor repository https://github.com/lensesio/stream-reactor/pull/801

There’s any estimation when we will have a new version to use this feature?

Otherwise  there’s any possibility to have a Milestone version to start using in lower environments until the official is released?

**Comment by davidsloan** [comment]
Closing as we released 3.0.0 
https://github.com/lensesio/stream-reactor/releases/tag/3.0.0
