### ISSUE TITLE
Hive: When I add new data to the Hive Database, but there is no new data in Kafka 

### ISSUE THREAD

**Issue by Jeson-gk** [lensesio/stream-reactor#807]
I used kafka-connect-hive.jar, kafka connect 
When i start kafka  connect task,  Successfully moved the data in hive to kafka ,
But when **new data** enters the hive database, there is **no new data in kafka**, how to solve it, thank you !!!

My configuration ：
connect.hive.database.name = default
connect.hive.fs.defaultFS = hdfs://hadoop:9000
connect.hive.hive.metastore = thrift
connect.hive.hive.metastore.uris = thrift://uri:19483
connect.hive.kcql = INSERT INTO hive_test SELECT * FROM test_test
connect.hive.poll.size = 1
connect.progress.enabled = true

**Comment by Jeson-gk** [comment]
connect.hive.refresh.frequency 
I also tried to set it up, but it still doesn't work

**Comment by davidsloan** [comment]
Closing due to deprecation of the hive connector.
