### ISSUE TITLE
All: Update to Confluent 6.1.x or 6.2.0

### ISSUE THREAD

**Issue by michaelandrepearce** [lensesio/stream-reactor#810]
Current version in dependency is getting old, as such its causing classpath conflicts occurring when using later versions of confluent platform kafka connect.

**Comment by davidsloan** [comment]
We have been working on an update to use Kafka 2.8.1 (Confluent 6.2.2) and Kafka 3.1.0 (Confluent 7.0.1).

This work has been merged down to master but not released yet.

Feel free to grab the branch and try it out.

**Comment by davidsloan** [comment]
Closing as this was released in October.
