### ISSUE TITLE
Output file write to S3 takes too long and flush config doesn't work on Amazon MSK Connect

### ISSUE THREAD

**Issue by jaehyeon-kim** [lensesio/stream-reactor#817]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?

3.3.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

Not sure which version is correct on Amazon MSK Connect.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?

Not sure what it means.

### Have you read the [docs](https://docs.lenses.io/connectors/)?

YES

### What is the expected behaviour?

Writing a JSON output file (approx less than 5KB) shouldn't take long. I expect it should take less than a second as reading a message from an Amazon MSK cluster takes around 200 ms.

### What was observed?

It takes too long to write output files to S3. Beginning with around 2-3 seconds, it gets slower and slower.

![image](https://user-images.githubusercontent.com/1023748/144669448-7b24e4c3-4540-4b81-9193-459824d31c28.png)

Also flush configuration doesn't work except for `WITH_FLUSH_COUNT = 1`.

Note checked the connector on (local) Confluent platform. It works very well. In general, its configuration is much more intuitive and I prefer over the Confluent S3 sink connector. However, as it doesn't work properly on MSK Connector, I have to use the Confluent one. 

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

Using MSK Connect

### What is your connector properties configuration (my-connector.properties)?

```
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
tasks.max=1
connect.s3.kcql=INSERT INTO <my-bucket>:<my-path> SELECT * FROM <my-topic> PARTITIONBY <my-field1>,<my-field2> STOREAS `json` WITH_FLUSH_COUNT = 1
aws.region=ap-southeast-2
aws.custom.endpoint=https://s3.ap-southeast-2.amazonaws.com/
topics=<my-topic>
key.converter.schemas.enable=false
schema.enable=false
errors.log.enable=true
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
```

### Please provide full log files (redact and sensitive information)

Here is a section of CloudWatch log message.

[log-events-viewer-result-connector.csv](https://github.com/lensesio/stream-reactor/files/7652248/log-events-viewer-result-connector.csv)

**Comment by davidsloan** [comment]
Thanks for raising this issue and for providing a detailed bug report!

Are you using msk connect in ap-southeast-2, same as your s3 bucket?

Regarding the flush configuration:

When the connector starts up it should print out a number of lines like this with how it processes the configuration:

`START: Executing ConfigDef processor {} with props {}`
`END: Executing ConfigDef processor {} with props {}`

These should give us some clues as to what is getting through to the connector from MSK Connect and what we're starting the connector with.  Of course you must remove any sensitive information.

Commit is a comparatively heavy operation as it involves multiple file operations and you wouldn't really expect to do it for each record.  If we figure out why the flush configuration is going missing then the performance should follow.

**Comment by jaehyeon-kim** [comment]
Hi @davidsloan 

The S3 bucket is created in `ap-southeast-2` and MSK connect runs in the same region. The connector has 2 related properties - `aws.region` and `aws.custom.endpoint`. The former doesn't seem to be recognized by a connector as I saw it is not printed in CloudWatch log. It sometimes causes an error without the latter configuration. That's why I added both the properties.

```
aws.region=ap-southeast-2
aws.custom.endpoint=https://s3.ap-southeast-2.amazonaws.com/
```

I searched CloudWatch with `ConfigDef` but didn't find the lines you indicated. 

![image](https://user-images.githubusercontent.com/1023748/144722423-21f5e69b-1182-4258-8d2e-2be04bce079b.png)

Flush configuration would help tackle down the performance issue but I wonder why it takes so much time to write a single file to S3. I played with a small data set of 829 records. When I tried on the local Confluent platform, it was quite quick. It gives a different story on MSM Connect. 

Let me know if you need further details.

Cheers,
Jaehyeon

**Comment by davidsloan** [comment]
Thanks for the reply @jaehyeon-kim .

That you can't see the lines in the log file makes me suspect that you might be using an outdated version - we only released 3.0.0 within the last few weeks.

Please can you double check that you are using the latest release 3.0.0 which is available at
https://github.com/lensesio/stream-reactor/releases/tag/3.0.0

**Comment by jaehyeon-kim** [comment]
Hi @davidsloan 

Thanks for your comment. I found 2.1.3 was used in the earlier attempt. I recreated another connector with the updated version 3.0.0 and no longer see the performance issue. Also I find the flush configuration works as well. Here is the updated configuration.

```
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
tasks.max=1
connect.s3.kcql=INSERT INTO <my-bucket>:<my-path> SELECT * FROM <my-topic> PARTITIONBY <my-field1>,<my-field2> STOREAS `json` WITH_FLUSH_INTERVAL = 60 WITH_FLUSH_COUNT = 50
aws.region=ap-southeast-2
aws.custom.endpoint=https://s3.ap-southeast-2.amazonaws.com/
topics=<my-topic>
key.converter.schemas.enable=false
schema.enable=false
errors.log.enable=true
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
```
And here is some log messages related to `ConfigDef`. I see `aws.region` is not recognized as well.

![image](https://user-images.githubusercontent.com/1023748/144727037-0c61e14e-fd79-4945-b205-58ca3f18d66d.png)

Finally I see an error `java.lang.UnsupportedOperationException: empty.maxBy`. In spite of it, the connector runs fine and could you please inform what creates that error?

[log-events-viewer-result-unsupported-operation-exception.csv](https://github.com/lensesio/stream-reactor/files/7654877/log-events-viewer-result-unsupported-operation-exception.csv)

Cheers,
Jaehyeon

**Comment by davidsloan** [comment]
Hi @jaehyeon-kim

Thanks for replying and testing against the latest version of the connector.

That's great news that the performance issue has gone.

I will prepare a fix to the UnsupportedOperationException that you have seen, and get back to you.

**Comment by jaehyeon-kim** [comment]
Thank you so much @davidsloan.

It's all good now. Please close this issue if necessary.

**Comment by mdimas** [comment]
Hi @davidsloan, I'm also seeing the `java.lang.UnsupportedOperationException: empty.maxBy` when running the 3.0.1 version of the S3SinkConnector on MSK Connect. It seems to be preventing the connector from resetting to the correct offset and being able to process any messages.

Are you still working on a fix for this?

Thanks,
Mark

**Comment by davidsloan** [comment]
Anyone still struggling with the `empty.maxBy` issue, please try the latest snapshot release if you are able:
https://drive.google.com/drive/folders/1egDmcFv3DQToUQnbUGEqZrgBKcFmQNKO

There are builds here for Kafka 2.8 and Kafka 3.1, please choose the correct one for your setup.

This will resolve the issue you have experienced.  This will make it into the next official release.

**Comment by ethanttbui** [comment]
@davidsloan if I don't fancy the idea of using a snapshot, which release would you recommend to avoid this issue? 🙏

**Comment by davidsloan** [comment]
Closing as this was released in October 😄
