### ISSUE TITLE
Can't build kafka-connect-cassandra on 3.0.1

### ISSUE THREAD

**Issue by ivanyu** [lensesio/stream-reactor#819]
Sorry for not using the issue template, most of the fields are "not applicable".

I checked out 3.0.1 tag in git and try to build the Cassandra connector with AdoptOpenJDK 8.0.292.hs-adpt:

```
$ git checkout 3.0.1
$ ./gradlew --no-daemon -Pversion=3.0.1 :kafka-connect-cassandra:shadowJar
```

I get this failure:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':kafka-connect-cassandra:shadowJar'.
> Could not resolve all files for configuration ':kafka-connect-cassandra:runtime'.
   > Could not find netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.45.Final).
     Searched in the following locations:
         file:/home/ivanyu/.m2/repository/io/netty/netty-transport-native-epoll/4.1.45.Final/netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar
```

The version is definitely in Maven Central: https://search.maven.org/artifact/io.netty/netty-transport-native-epoll/4.1.45.Final/jar, but Gradle won't even look there.

I tried clearing Gradle and Maven caches, too.

Other connectors seem to build quite OK.

**Comment by davidsloan** [comment]
Unless there's a reason you need to build from source, it can be easier to use the jars we've already built.

Please see our releases page for pre-built jars:

https://github.com/lensesio/stream-reactor/releases

**Comment by ivanyu** [comment]
I'm afraid I do have a reason to build from source :)

**Comment by davidsloan** [comment]
> I'm afraid I do have a reason to build from source :)

Glad to hear it.  Do you care to share it?  Perhaps we can help.

Do you have a PR showing your changes?  As the only reason I can see that this would be happening is if some of the dependencies have changed.

**Comment by ivanyu** [comment]
My company is providing Kafka Connect with some connectors as a service. It's really important for us to be in control of what we ship and for this we need reproducible builds from source.

I tried building on a different machine and it worked. So obviously the problem is on my side. Sorry for the false alarm 🙏

**Comment by davidsloan** [comment]
Thanks for letting us know, glad you got it sorted.  Shout out if you need any more assistance @ivanyu .
