### ISSUE TITLE
java.lang.ClassNotFoundException: javax.crypto.Cipher

### ISSUE THREAD

**Issue by dmarupov** [lensesio/stream-reactor#820]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
Connector Version 3.0.1
### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Kafka Version 2.8
### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
No
### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes
### What is the expected behaviour?
ClassNotFoundException 
Can't find javax.crypto.Cipher
### What was observed?
When attempting to create the connector the ClassNotFoundException occurs. I am trying to see if anybody else is having the same issue. Also, I am using the open source version of java and I hope that is not the issue?
### What is your Connect cluster configuration (connect-avro-distributed.properties)?
None for Avro
### What is your connector properties configuration (my-connector.properties)?
It is vanilla
### Please provide full log files (redact and sensitive information)
```
Caused by: java.lang.ClassNotFoundException: javax.crypto.Cipher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 77 more
```

**Comment by andrewstevenson** [comment]
@dmarupov which connector?

**Comment by dmarupov** [comment]
> @dmarupov which connector?

Oh sorry this is for AWS S3 connector.

**Comment by dmarupov** [comment]
I think I found my issue. What was causing this issue for me is that I had multiple versions of the AWS S3 connector jar file in my plugin directory.
