### ISSUE TITLE
AWS S3 Source Connector unable to process/read JSON files from S3 Bucket. 

### ISSUE THREAD

**Issue by dmarupov** [lensesio/stream-reactor#823]
### What version of the Stream Reactor are you reporting this issue for?
I am using `kafka-connect-aws-s3-3.0.1-2.5.0-all.jar`

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
I am using Kafka 2.8 version.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
No

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes
Connector plugin is loading correctly and I am able to process/read `*.text` files from the S3 bucket.

### What is the expected behaviour?
It should be processing/reading `*.JSON` files from the S3 bucket.

### What was observed?
Files with `*.JSON` format are not being processed/read. No errors, meaning the connector is not failing. Still able to process `*.text` files.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
None
### What is your connector properties configuration (my-connector.properties)?
`connect-standalone.properties`:
```
bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.file.filename=/data/connect.offsets
offset.flush.interval.ms=10000
plugin.path=/opt/connectors
```

**Comment by davidsloan** [comment]
@dmarupov can you share your kcql configuration string too please?

Also logs would be helpful.  Remember to remove anything sensitive from these.

**Comment by dmarupov** [comment]
@davidsloan ,

Here is my KCQL that I used for `text` and `json`:
```
"insert into kafka-topic select * from s3-bucket-name:s3-bucket-directory STOREAS `text`"
"insert into kafka-topic select * from s3-bucket-name:s3-bucket-directory STOREAS `json`"
```

I will try to get some logs.

**Comment by dmarupov** [comment]
I just tried to process some files this morning and I got mixed results:
![image](https://user-images.githubusercontent.com/46696879/146973213-5e59a797-1885-47be-8193-330e8438eb87.png)
This is a screenshot of my S3 Bucket and as you can see I have three differently named JSON files that come with sequenced numbers to make it easier for testing. But out of all these files it will only process files named `toodlesXX.json` and not the other ones.

Here is the connect.log:
```
ef:177)
[2021-12-21 11:19:19,216] INFO S3ConfigDefBuilder values:
        connect.s3.aws.access.key = [hidden]
        connect.s3.aws.auth.mode = Credentials
        connect.s3.aws.region = my-region-n
        connect.s3.aws.secret.key = [hidden]
        connect.s3.custom.endpoint =
        connect.s3.disable.flush.count = false
        connect.s3.error.policy = THROW
        connect.s3.http.max.retries = 5
        connect.s3.http.retry.interval = 50
        connect.s3.kcql = insert into kafka-topic select * from s3-bucket-name:s3-bucket-directory STOREAS `json`
        connect.s3.local.tmp.directory =
        connect.s3.max.retries = 20
        connect.s3.retry.interval = 60000
        connect.s3.vhost.bucket = false
 (io.lenses.streamreactor.connect.aws.s3.config.S3ConfigDefBuilder:372)

[2021-12-21 11:19:21,177] INFO WorkerSourceTask{id=S3SourceConnector-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:225)
[2021-12-21 11:19:59,555] INFO [S3SourceConnector] Reading next file: RemoteS3PathLocation(s3-bucket-name,Some(s3-bucket-directory),s3-bucket-directory/toodles04.json) from line -1 (io.lenses.streamreactor.connect.aws.s3.source.reader.ReaderCreator:30)
[2021-12-21 11:29:08,839] INFO WorkerSourceTask{id=S3SourceConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:487)
[2021-12-21 11:29:09,469] INFO [S3SourceConnector] Reading next file: RemoteS3PathLocation(s3-bucket-name,Some(s3-bucket-directory),s3-bucket-directory/toodles05.json) from line -1 (io.lenses.streamreactor.connect.aws.s3.source.reader.ReaderCreator:30)
[2021-12-21 11:29:18,839] INFO WorkerSourceTask{id=S3SourceConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:487)
```

I tried manually uploaded these differently named JSON files but it only seems to process one and not the others. And I don't see any errors.

**Comment by davidsloan** [comment]
Hi @dmarupov , Happy New Year.  Apologies for the delay but I was out on Christmas break.

Do you see this problem when you create it as a new connector from scratch?

For an existing connector, Kafka Connect maintains the state so the connector is designed to resume from after the last file that was processed.

Also, it uses the ascii ordering so will miss files if you add them before one that's already been processed.

If you successfully process test01.json and then add newtest01.json (which could be what happened according to your last modified times) then newtest01.json will never be picked up.

Could this explain your problem?

**Comment by davidsloan** [comment]
Closing as ticket inactive for 2 months.  Please add more detail if you are still experiencing a problem.
