### ISSUE TITLE
S3 Sink Connector always call GetBucketLocation in us-east-1

### ISSUE THREAD

**Issue by jeevanullas** [lensesio/stream-reactor#826]
# Issue Guidelines

Please review these questions before submitting any issue?
Completed.

### What version of the Stream Reactor are you reporting this issue for?
3.0.1

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Kafka version - Amazon MSK 2.7.1 - This cluster is running inside a private only network (VPC) with access to Amazon S3 using VPC Endpoint. 3 Brokers across 3 availability zones running m5.large instance type with 10GiB disk space and MSK IAM Authentication only.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
kafka-connect-aws-s3-3.0.1-2.5.0-all.jar

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is the expected behaviour?
S3 Sink connector should honour the s3 endpoint / region config properties and leverage that to call GetBucketLocation on the specified backup bucket.

### What was observed?
```
SEVERE: Cannot retry after server error, command has exceeded retry limit 5: [method=org.jclouds.aws.s3.AWSS3Client.public abstract java.lang.String org.jclouds.s3.S3Client.getBucketLocation(java.lang.String)[<backup-bucket>], request=GET https://s3.amazonaws.com/<backup-bucket>?location HTTP/1.1]
```

As seen above the S3 Sink connector tries to call the us-east-1 specific endpoint ```s3.amazonaws.com``` as specified per documentation here - https://docs.aws.amazon.com/general/latest/gr/s3.html (note Amazon S3 Endpoint section and us-east-1 Northern Virginia).

If I specify a NAT gateway to the VPC Subnet where Kafka is running this same configuration works as it unblocks the connector to communicate with ```s3.amazonaws.com``` in Northern Virginia (us-east-1).

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

```
auto.create.topics.enable=true
default.replication.factor=3
min.insync.replicas=2
num.io.threads=8
num.network.threads=5
num.partitions=1
num.replica.fetchers=2
replica.lag.time.max.ms=30000
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
unclean.leader.election.enable=true
zookeeper.session.timeout.ms=18000
delete.topic.enable=true
log.retention.hours=-1
log.retention.bytes=-1
```

### What is your connector properties configuration (my-connector.properties)?

Note below I have tried both ```connect.s3.vhost.bucket``` as ```true``` and ```false``` with same end result. 

```
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
tasks.max=1
topics=<kafka topic>
connect.s3.vhost.bucket=true
schema.enable=false
key.converter.schemas.enable=false
connect.s3.kcql=INSERT INTO <backup bucket>:<prefix> SELECT * FROM <kafka topic> STOREAS `json` WITH_FLUSH_INTERVAL = 60 WITH_FLUSH_COUNT = 50
aws.region=ap-southeast-2
aws.custom.endpoint=https://s3.ap-southeast-2.amazonaws.com/
value.converter.schemas.enable=false
connect.s3.aws.region=ap-southeast-2
value.converter=org.apache.kafka.connect.storage.StringConverter
errors.log.enable=true
key.converter=org.apache.kafka.connect.storage.StringConverter
```

### Please provide full log files (redact and sensitive information)
[error.log](https://github.com/lensesio/stream-reactor/files/7939420/error.log)

Also, for sanity check purposes the IAM policy attached to the IAM Role used by the connector to access Amazon S3 is below - 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::backup-bucket"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::backup-bucket",
                "arn:aws:s3:::backup-bucket/*"
            ]
        }
    ]
}
```

**Comment by jeevanullas** [comment]
I realised that aws.* properties have been deprecated and replaced with new ones as per PR - https://github.com/lensesio/stream-reactor/pull/791 so I replaced my configuration accordingly but that did not make any difference (both with vhost enabled and disabled). I can also confirm that exact same problem is impacting S3 Source connector. Note that both S3 bucket (backup bucket), Kafka (Kafka and Kafka connect) resides in ap-southeast-2. S3 VPC endpoints cannot serve cross-region requests - https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html so it would be upon the client to use region specific endpoints.

**Comment by funes79** [comment]
I had a similar issue:
```
[Worker-0a412755b800bdc42] org.jclouds.aws.AWSResponseException: request GET https://<BUCKET NAME>.s3.amazonaws.com/?prefix=tutorial&max-keys=1000 HTTP/1.1 failed with code 400, error: AWSError{requestId='xxxx', requestToken=xxxx=', code='AuthorizationHeaderMalformed', message='The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'', context='{Region=eu-west-1, HostId=xxxxx=}'
```

Used both style of setting in the config file, but none of them worked.
```
connect.s3.aws.region=eu-west-1
aws.region=eu-west-1
```

**Comment by AliBrahem** [comment]
Hello,
Any update on this issue please ?

**Comment by davidsloan** [comment]
> Hello, Any update on this issue please ?

@AliBrahem if you reach out to me on our [community slack](https://launchpass.com/lensesio) I can share a build designed to use the AWS library instead of JClouds.  Any help testing would be welcome.

**Comment by Lucas3oo** [comment]
So basically you can't use VPC endpoints for S3 with this connector?

I also see that the connector calls https://s3.amazonaws.com/my-bucket?location 
regardless how I configure aws.region and aws.custom.endpoint

**Comment by davidsloan** [comment]
> So basically you can't use VPC endpoints for S3 with this connector?
> I also see that the connector calls https://s3.amazonaws.com/my-bucket?location regardless how I configure aws.region and aws.custom.endpoint

Yes this seems to be something that the jClouds library is doing at a lower level and there is no way to prevent that short of submitting an issue report/pull request to that project.

I have been working on an update which enables the AWS library to be used instead, but this will need another day or so before it's ready to test.

**Comment by davidsloan** [comment]
Anyone still struggling with this, please try the latest snapshot release if you are able:

https://drive.google.com/drive/folders/1egDmcFv3DQToUQnbUGEqZrgBKcFmQNKO

There are builds here for Kafka 2.8 and Kafka 3.1, please choose the correct one for your setup.

If you add the extra configurations:

```
connect.s3.aws.client=AWS
connect.s3.aws.region=eu-west-1
```

Then this will use the AWS S3 client internally instead of jClouds, therefore avoiding this problem.

Please feedback whether this resolves the issue you have experienced.

**Comment by caseycrites** [comment]
hey @davidsloan! looks like this fix got merged. any idea when it might be released?

**Comment by aidan-melen** [comment]
> connect.s3.aws.client=AWS
> connect.s3.aws.region=eu-west-1

I can confirm that this does not work with the latest [release (3.0.1)](https://github.com/lensesio/stream-reactor/releases/tag/3.0.1)

**Comment by aidan-melen** [comment]
UPDATE: I built my own fat jar with `sbt "project aws-s3-kafka-3-1" assembly` and then I was able to use the `connect.s3.aws.client=AWS` property. That being said, the project has not yet released this jar as far as I can tell.

**Comment by davidsloan** [comment]
@caseycrites this was released in October - apologies, I missed the reply as the ticket was closed.

https://github.com/lensesio/stream-reactor/releases/tag/4.0.0
