### ISSUE TITLE
232  vulnerabilities found in S3 and common projects dependencies using OWASP dependecyCheck

### ISSUE THREAD

**Issue by Lucas3oo** [lensesio/stream-reactor#843]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
3.0.1

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
n/a
### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
n/a
### Have you read the [docs](https://docs.lenses.io/connectors/)?
yes
### What is the expected behaviour?

Hi
I run OWASP dependency check plugin 
id 'org.owasp.dependencycheck' version '6.5.0.1'
on the kafka-connect-aws-s3 project and found about  232 vulnerabilities.
Mostly in Jackson, Netty and net.minidev jars.

Any plans to dump the version on 3:rd party libs?

**Comment by davidsloan** [comment]
Thanks for the report.

Actually we have been working towards a new release with newer versions of many of these dependencies.

Running your scan tool (which is great, thank you for that) on it I can see there are now around 30 vulnerabilities.

No more issues in the Jackson dependencies, for example.

We will put some effort into clearing up the remaining dependency issues.

Feel free to check out our master branch and re-run your tool.

**Comment by Lucas3oo** [comment]
Yeah, I will do that again :-)
