### ISSUE TITLE
S3 source connector get stuck after a while when running in standalone mode

### ISSUE THREAD

**Issue by ethanttbui** [lensesio/stream-reactor#861]
# Issue Guidelines

S3 source connector get stuck after a while when running in `standalone` mode

### What version of the Stream Reactor are you reporting this issue for?

I'm using the snapshot provided here https://github.com/lensesio/stream-reactor/issues/817#issuecomment-1111012565

`kafka-connect-aws-s3-kafka-2-8-assembly-1.1-SNAPSHOT.jar`

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

I'm running Kafka version 2.8.1

### What is the expected behaviour?

I expect that S3 source connector can read all files produced by the sink connector

### What was observed?

S3 source connector get stuck after some offsets.

Latest offset of the original topic is 35:
![Screen Shot 2022-06-14 at 13 27 55](https://user-images.githubusercontent.com/14036270/173487352-6adac973-dedb-4d5c-aa15-ed7b1417009f.png)
Which has been correctly stored to S3 by the sink connector:
![Screen Shot 2022-06-14 at 13 29 02](https://user-images.githubusercontent.com/14036270/173487413-56a7fa03-7af8-4fb8-a7d5-7e1976807dc9.png)

But the source connector got stuck at offset (17)
![Screen Shot 2022-06-14 at 13 28 03](https://user-images.githubusercontent.com/14036270/173487608-eb73d409-129b-40c9-8e3f-4df27632af32.png)

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
standalone connect properties
```
bootstrap.servers=flow-kafka:9092
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
plugin.path=/project/s3-connect/connectors

```

### What is your connector properties configuration (my-connector.properties)?
Sink connector
```
name=flow-s3-sink-connector
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
topics=exposure-signal,gib-exposure-signal
tasks.max=1
connect.s3.kcql=insert into flow-kafka-store:backup select * from exposure-signal STOREAS `Bytes_KeyAndValueWithSizes` WITH_FLUSH_COUNT = 3; \
    insert into flow-kafka-store:backup select * from gib-exposure-signal STOREAS `Bytes_KeyAndValueWithSizes` WITH_FLUSH_COUNT = 3
connect.s3.aws.region=ap-northeast-1
connect.s3.custom.endpoint=http://flow-localstack:4566
connect.s3.vhost.bucket=true
aws.access.key=local
aws.secret.key=local
aws.auth.mode=Credentials
```

Source connector
```
name=flow-s3-source-connector
connector.class=io.lenses.streamreactor.connect.aws.s3.source.S3SourceConnector
topics=exposure-signal_restored,gib-exposure-signal_restored
tasks.max=1
connect.s3.kcql=insert into exposure-signal_restored select * from flow-kafka-store:backup/exposure-signal STOREAS `Bytes_KeyAndValueWithSizes`; \
    insert into gib-exposure-signal_restored select * from flow-kafka-store:backup/gib-exposure-signal STOREAS `Bytes_KeyAndValueWithSizes` 
connect.s3.aws.region=ap-northeast-1
connect.s3.custom.endpoint=http://flow-localstack:4566
connect.s3.vhost.bucket=true
aws.access.key=local
aws.secret.key=local
aws.auth.mode=Credentials
```

### Please provide full log files (redact and sensitive information)
[source_connector.log](https://github.com/lensesio/stream-reactor/files/8896151/source_connector.log)

And here's the connect.offsets file:
```
��srjava.util.HashMap���`�F
loadFactorI	thresholdxp?@
                             ur[B��T�xp_["flow-s3-source-connector",{"container":"flow-kafka-store","prefix":"backup/exposure-signal"}]uq~7{"path":"backup/exposure-signal/0/98.bytes","line":"2"}uq~c["flow-s3-source-connector",{"container":"flow-kafka-store","prefix":"backup/gib-exposure-signal"}]uq~:{"path":"backup/gib-exposure-signal/0/8.bytes","line":"2"}x
```

**Comment by ethanttbui** [comment]
@davidsloan could you please take a look at this issue?

**Comment by ethanttbui** [comment]
@davidsloan may I ask when this issue is expected to be resolved? 🙏

**Comment by fqlx** [comment]
Did you find a workout?  It `JsonConverter` worked for me but no `ByteArrayConverter`

**Comment by davidsloan** [comment]
The S3 Source connector has undergone a rewrite for reliability and many bugs were fixed since this issue was raised and this problem has been fixed.
