### ISSUE TITLE
S3 Source Connector not flushing anything

### ISSUE THREAD

**Issue by ewinata** [lensesio/stream-reactor#864]
Hi guys, I am trying to connect the s3 source connector to a minio instance. The creation of the Kafka connector is fine but nothing gets logged out after source task is being executed. I have tried adding files onto the bucket and nothing happens.

**What version of the Stream Reactor are you reporting this issue for?**
I'm using the current latest build unzipped from kafka-connect-aws-s3-3.0.1-2.5.0-all.tar.gz

**Are you running the correct version of Kafka/Confluent for the Stream reactor release?**
I'm running Kafka version 3.2.0

**What is the expected behaviour?**
I expect that S3 source connector would flush files onto my topic

**What was observed?**
After log on Kafka shows Executing source task, nothing gets flushed in even after adding files to the bucket 'testnotifications'

[2022-06-22 05:28:04,625] INFO [con2|task-0] S3ConfigDefBuilder values:
        connect.s3.aws.access.key = [hidden]
        connect.s3.aws.auth.mode = Credentials
        connect.s3.aws.region = us-west-2
        connect.s3.aws.secret.key = [hidden]
        connect.s3.custom.endpoint = *********************
        connect.s3.error.policy = THROW
        connect.s3.http.max.retries = 5
        connect.s3.http.retry.interval = 50
        connect.s3.kcql = insert into epsilon select * from testnotifications: STOREAS `Bytes_ValueOnly`
        connect.s3.local.tmp.directory =
        connect.s3.max.retries = 20
        connect.s3.retry.interval = 60000
        connect.s3.vhost.bucket = true
 (io.lenses.streamreactor.connect.aws.s3.config.S3ConfigDefBuilder:376)
[2022-06-22 05:28:04,659] INFO [con2|task-0] WorkerSourceTask{id=con2-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:227)
[2022-06-22 05:28:04,660] INFO [con2|task-0] WorkerSourceTask{id=con2-0} Executing source task (org.apache.kafka.connect.runtime.WorkerSourceTask:233)

**Comment by davidsloan** [comment]
I would recommend building the `master` version of the connector as it has had many enhancements since the last release.

(They will be included in the next release)

Let me know if this resolves the issue.

**Comment by aidan-melen** [comment]
Hi @davidsloan I am experiencing a similar issue with a build from `master`. The s3 source connector flushes all of the messages contained in S3 initially. However, I am noticing that all new messages written to S3 are not flushed by the S3 source connector.

**Comment by aidan-melen** [comment]
^^^ on second thought, this may be more related to https://github.com/lensesio/stream-reactor/issues/861

**Comment by kr-jojo** [comment]
@ewinata  @aidan-melen  @davidsloan  may I ask when this issue is expected to be resolved? 🙏

**Comment by ayushagr707** [comment]
@aidan-melen I am encountering the same issue. The connector is working only right after the creation. At a later stage, the S3 source connector is not writing the files from S3 to Kafka topic. Were you able to resolve the issue?

**Comment by ayushagr707** [comment]
Hi @davidsloan Just wanted to check if this issue is related to the source connector plugin or am I missing anything important in the configuration. I have tested this multiple times but the files from S3 are getting streamed to Kafka topic on a random basis and not always

**Comment by davidsloan** [comment]
> Hi @davidsloan Just wanted to check if this issue is related to the source connector plugin or am I missing anything important in the configuration. I have tested this multiple times but the files from S3 are getting streamed to Kafka topic on a random basis and not always

We are aware of the issue with the S3 Source that we are currently investigating.  We hope to have a fix in our next release.

**Comment by stheppi** [comment]
Please try the latest release. This issue should be fixed
