### ISSUE TITLE
AWS S3 Sink connector does not store Kafka message key

### ISSUE THREAD

**Issue by YordanPavlov** [lensesio/stream-reactor#869]
### What version of the Stream Reactor are you reporting this issue for?

Latest master build

### What is the expected behaviour?

The S3 sink connector to store the Kafka message along with its key inside S3.

### What was observed?

The Kafka message key is ignored and only the value is stored.

### What is your Connect cluster configuration (connect-avro-distributed.properties)?

```
bootstrap.servers=kafka:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
plugin.path=/home/src/kafka/jars
group.id=kafka-connect
storage.topic=_connect-configs
offset.storage.topic=_connect-offsets
status.storage.topic=_connect-status
```

### What is your connector properties configuration (my-connector.properties)?

```
name=S3SinkConnectorS3 # this can be anything
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
tasks.max=1
aws.auth.mode=Default
topics=test_yordan_kafka_connect
connect.s3.kcql="insert into `test:test-bucket` select * from test_yordan_kafka_connect STOREAS `JSON` WITH_FLUSH_COUNT = 5000"
connect.s3.aws.client=AWS
connect.s3.aws.region=eu-central-1
timezone=UTC
errors.log.enable=true
```

I did some debugging of the codebase and suspect the issue is the key is being ignored here:
https://github.com/lensesio/stream-reactor/blob/master/kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/JsonFormatWriter.scala#L41

**Comment by davidsloan** [comment]
Hello, thanks for raising this.

Exactly what you ask is not supported because Kafka Connect is flexible and there are other ways to solve this problem.  Just some ideas:

1. You could use SMTs before reaching the connector to insert the keys into the message/otherwise transform the message.  Two suggestions are:
    1. Combine [headerfrom](https://docs.confluent.io/platform/current/connect/transforms/headerfrom.html#headerfrom) with [insertfield](https://docs.confluent.io/platform/current/connect/transforms/insertfield.html#insertfield) to extract the desired part of your key into the header and then insert it into your value
    2. The [connect-transform-archive](https://github.com/jcustenborder/kafka-connect-transform-archive) SMT is able to combine the key value and message headers into a single message value.
2. Without using SMTs, you can switch from Json to bytes (eg Bytes_KeyAndValueWithSizes).  The output file will not be a json doc though.
3. Without using SMTs, you can write the key(s) you want to keep in the stored filename path using custom partitioning.

Hope this helps!  Please close the issue if this helps to resolve your problem.

**Comment by iosifnicolae2** [comment]
The second solution seems not to work because we're getting https://github.com/lensesio/stream-reactor/issues/877.

**Comment by iosifnicolae2** [comment]
The ideal solution would be to save everything from Kafka (including timestamp, key, value, headers) as json files in S3.

**Comment by iosifnicolae2** [comment]
Also, I've tried the idea 1.ii by adding
```
"transforms" : "archiveRowForS3",
"transforms.archiveRowForS3.type" : "com.github.jcustenborder.kafka.connect.archive.Archive",
```
but I'm getting:
```java
java.lang.UnsupportedOperationException: empty.maxBy
--
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.TraversableOnce.maxBy(TraversableOnce.scala:282)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.TraversableOnce.maxBy$(TraversableOnce.scala:280)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.AbstractTraversable.maxBy(Traversable.scala:108)
Wed, Aug 31 2022 9:32:35 pm | at io.lenses.streamreactor.connect.aws.s3.sink.S3WriterManager.io$lenses$streamreactor$connect$aws$s3$sink$S3WriterManager$writerForTopicPartitionWithMaxOffset(S3WriterManager.scala:68)
Wed, Aug 31 2022 9:32:35 pm | at io.lenses.streamreactor.connect.aws.s3.sink.S3WriterManager$anonfun$preCommit$1.applyOrElse(S3WriterManager.scala:244)
Wed, Aug 31 2022 9:32:35 pm | at io.lenses.streamreactor.connect.aws.s3.sink.S3WriterManager$anonfun$preCommit$1.applyOrElse(S3WriterManager.scala:242)
Wed, Aug 31 2022 9:32:35 pm | at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.TraversableLike.collect(TraversableLike.scala:407)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.TraversableLike.collect$(TraversableLike.scala:405)
Wed, Aug 31 2022 9:32:35 pm | at scala.collection.AbstractTraversable.collect(Traversable.scala:108)
Wed, Aug 31 2022 9:32:35 pm | at io.lenses.streamreactor.connect.aws.s3.sink.S3WriterManager.preCommit(S3WriterManager.scala:242)
Wed, Aug 31 2022 9:32:35 pm | at io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask.preCommit(S3SinkTask.scala:181)
Wed, Aug 31 2022 9:32:35 pm | at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:387)
Wed, Aug 31 2022 9:32:35 pm | at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:639)
Wed, Aug 31 2022 9:32:35 pm | at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:202)
Wed, Aug 31 2022 9:32:35 pm | at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
Wed, Aug 31 2022 9:32:35 pm | at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
Wed, Aug 31 2022 9:32:35 pm | at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Wed, Aug 31 2022 9:32:35 pm | at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Wed, Aug 31 2022 9:32:35 pm | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Wed, Aug 31 2022 9:32:35 pm | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Wed, Aug 31 2022 9:32:35 pm | at java.base/java.lang.Thread.run(Thread.java:829)
Wed, Aug 31 2022 9:32:35 pm | 2022-08-31 18:32:35,891 ERROR WorkerSinkTask{id=main-kafka-raw-packets-to-s3-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-main-kafka-raw-packets-to-s3-0]
```
Without the transformer the data is pushed to S3 correctly.

**Comment by iosifnicolae2** [comment]
We've solved this problem by following these steps:
1. Implement `JsonFormatStreamReader` - https://github.com/iosifnicolae2/stream-reactor
2. Implement Archive & UnArchive transformers - https://github.com/iosifnicolae2/kafka-connect-transform-archive
   - you can use this [Dockerfile](https://github.com/iosifnicolae2/kafka-connect-transform-archive/blob/master/Dockerfile) to build the plugin and include it in your Kafka Connector
3. Configure your Sink connector using:
```
"connect.s3.kcql" : "insert into XXXX:XX select * from YYYY STOREAS `JSON` WITH_FLUSH_INTERVAL=60 WITH_FLUSH_COUNT=1000"
"transforms" : "archiveRowForS3",
"transforms.archiveRowForS3.type" : "com.github.jcustenborder.kafka.connect.archive.Archive",
```
4. Configure your Source connector using:
```
"connect.s3.kcql" : "insert into YYYY select * from XXXX:xxx  BATCH = 5 STOREAS `JSON` LIMIT 1000"
"transforms" : "archiveRowForS3",
"transforms.archiveRowForS3.type" : "com.github.jcustenborder.kafka.connect.archive.Archive",
```

**Comment by stheppi** [comment]
The katest version of stream-reactor supports storing the entire payload (key, value, headers, timestamp, partition, offset, topic).
Check the documentation [here](https://docs.lenses.io/5.4/connectors/sinks/s3sinkconnector/). It requires the setting `store.envelope` to be set to true.
