### ISSUE TITLE
Support gzip compression for S3 connector

### ISSUE THREAD

**Issue by akamac** [lensesio/stream-reactor#875]
It would be nice if S3 source/sink connectors could support reading/dumping gzip files.

**Comment by davidsloan** [comment]
We have worked on adding the compression codec support for Parquet and Avro files.  Not quite what you've asked for but I wonder if this would be helpful to you?

**Comment by iaon** [comment]
The compression for Json files will be very useful too.

**Comment by davidsloan** [comment]
For the sink, @brandon-powers work has now been released in https://github.com/lensesio/stream-reactor/releases/tag/6.1.0

**Comment by stheppi** [comment]
Since this feature is covered, we are closing this issue.

**Comment by PrekshyaBasnet** [comment]
Will there be gzip compression for S3 source connector?
