### ISSUE TITLE
4.0.0 Release Documentation Missing

### ISSUE THREAD

**Issue by jdeex** [lensesio/stream-reactor#882]
Please see the [Stream Reactor Release Notes at Lenses Documentation](https://docs.lenses.io/4.3/integrations/connectors/sr-release-notes/).

That link in the front page doesn't show version 4.0.0 and also states that "You are viewing documentation for an older version of Lenses.io View [latest documentation here](https://docs.lenses.io/current/integrations/connectors/sr-release-notes/)"

Then in the latest version 4.0.0 is also missing

**Comment by davidsloan** [comment]
The new release notes are now available here: https://docs.lenses.io/5.0/integrations/connectors/sr-release-notes/
