### ISSUE TITLE
S3 source connector - fix the document

### ISSUE THREAD

**Issue by vikshab** [lensesio/stream-reactor#883]
The [README ](https://github.com/lensesio/stream-reactor/blob/master/kafka-connect-aws-s3/README-source.md#credentials) of the S3 source connector states `... with permissions to write to the desired S3 bucket.`

The S3 source connector should have the following permissions
-  `ListBucket`
- `GetObject`

It's not writing anything to the bucket, but retrieving objects from it

**Comment by davidsloan** [comment]
Thank you for reporting, you are absolutely right - I have fixed the docs now

https://docs.lenses.io/5.2/connectors/sources/s3sourceconnector/
