### ISSUE TITLE
s3 prefix recognition issue in s3 source connector

### ISSUE THREAD

**Issue by kr-jojo** [lensesio/stream-reactor#888]
I am trying to use lenses s3 source connector in aws msk(version 2.7.2)
Download kafka-connect-aws-s3-kafka-3-1-4.0.0.zip as a plug-in, save it in S3 and register it. 
And the above plug-in was specified and the connector configuration was written as follows.  

### What version of the Stream Reactor are you reporting this issue for?
kafka-connect-aws-s3-kafka-3-1-4.0.0.zip

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
I'm running Kafka version 2.7.2

### What is your connector properties configuration (my-connector.properties)?
[Connector Configuration]
```
connector.class=io.lenses.streamreactor.connect.aws.s3.source.S3SourceConnector
key.converter.schemas.enable=false
connect.s3.kcql=insert into my_topic select * from  my_bucket:dev/domain_name/year=2022/month=11/ STOREAS 'JSON'
tasks.max=2
connect.s3.aws.auth.mode=Default
value.converter.schemas.enable=false
connect.s3.aws.region= ap-northeast-2
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
```

### What was observed?
The connector is normally created and data is read from S3 to the specified topic, but there are two problems here.

1. As described in "connect.s3.kcql", data is imported based on /year=2022/month=11/, but other partitioned month and date data are also imported. It seems that the paths of "/year=" and "/month= " specified under /dev/domain_name(=PREFIX_NAME) are not recognized and all are imported. I wonder if there is a way.
(refer to my full s3 path: my_bucket/dev/domain_name/year=2022/month=11/hour=1/*.json )

2. The json file exists more in the specified s3 path, but it is no longer imported into the topic. No errors occur and this is normal. When I look at the log messages, the below repeats over and over again.

```
INFO [S3-Source-Connector-Dev|task-1|offsets] WorkerSourceTask{id=S3-Source-Connector-Dev-1} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:485)
INFO [S3-Source-Connector-Dev|task-1|offsets] WorkerSourceTask{id=S3-Source-Connector-Dev-1} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:502)
```

### What is the expected behavior?

1. Only the files corresponding to the specified  "/year=" and "/month= "  should be read and saved in the topic.

2. Files are accumulated in real time, so I need to save them to the topic right away.

please help me..

**Comment by davidsloan** [comment]
Hi @kr-jojo .

Sorry for the delay in replying.  There is a simple fix, and that is to use backticks "`" to quote the source value that is getting truncated as well as the `STOREAS` value.

    connect.s3.kcql=insert into my_topic select * from `my_bucket:dev/domain_name/year=2022/month=11/` STOREAS `JSON`


Hope this helps!
