### ISSUE TITLE
Elastic6 and Elastic7 ExceptionInInitializerError JsonMappingException

### ISSUE THREAD

**Issue by jdeex** [lensesio/stream-reactor#892]
Hello @davidsloan, we have tested the latest release 4.0.0 for Kafka 3.1 and we are facing the same old error for Elastic6 and Elastic7 connectors. 

See logs below:

[kafka-connect-elastic6-kafka-3-1-4.0.0.zip](https://github.com/lensesio/stream-reactor/releases/download/4.0.0/kafka-connect-elastic6-kafka-3-1-4.0.0.zip) - Scala module 2.13.3 requires Jackson Databind version >= 2.13.0 and < 2.14.0
[kafka-connect-elastic7-kafka-3-1-4.0.0.zip](https://github.com/lensesio/stream-reactor/releases/download/4.0.0/kafka-connect-elastic7-kafka-3-1-4.0.0.zip) - Scala module 2.13.3 requires Jackson Databind version >= 2.13.0 and < 2.14.0

`kafka-connect-1  | java.lang.ExceptionInInitializerError
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.Transform$.apply(Transform.scala:97)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticJsonWriter.$anonfun$insert$5(ElasticJsonWriter.scala:126)
kafka-connect-1  |      at scala.collection.immutable.Vector1.map(Vector.scala:1872)
kafka-connect-1  |      at scala.collection.immutable.Vector1.map(Vector.scala:375)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticJsonWriter.$anonfun$insert$4(ElasticJsonWriter.scala:119)
kafka-connect-1  |      at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
kafka-connect-1  |      at scala.collection.mutable.Growable.addAll(Growable.scala:62)
kafka-connect-1  |      at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
kafka-connect-1  |      at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:142)
kafka-connect-1  |      at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:42)
kafka-connect-1  |      at scala.collection.mutable.GrowableBuilder.addAll(GrowableBuilder.scala:34)
kafka-connect-1  |      at scala.collection.mutable.GrowableBuilder.addAll(GrowableBuilder.scala:25)
kafka-connect-1  |      at scala.collection.mutable.Builder$$anon$1.addAll(Builder.scala:81)
kafka-connect-1  |      at scala.collection.mutable.Builder$$anon$1.addAll(Builder.scala:78)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
kafka-connect-1  |      at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticJsonWriter.$anonfun$insert$1(ElasticJsonWriter.scala:114)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
kafka-connect-1  |      at scala.collection.immutable.HashMap.flatMap(HashMap.scala:39)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticJsonWriter.insert(ElasticJsonWriter.scala:104)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticJsonWriter.write(ElasticJsonWriter.scala:95)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticSinkTask.$anonfun$put$2(ElasticSinkTask.scala:71)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticSinkTask.$anonfun$put$2$adapted(ElasticSinkTask.scala:71)
kafka-connect-1  |      at scala.Option.foreach(Option.scala:437)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic7.ElasticSinkTask.put(ElasticSinkTask.scala:71)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
kafka-connect-1  |      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
kafka-connect-1  |      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-connect-1  |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
kafka-connect-1  |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
kafka-connect-1  |      at java.base/java.lang.Thread.run(Thread.java:829)
kafka-connect-1  | Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.13.3 requires Jackson Databind version >= 2.13.0 and < 2.14.0
kafka-connect-1  |      at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
kafka-connect-1  |      at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
kafka-connect-1  |      at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
kafka-connect-1  |      at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
kafka-connect-1  |      at com.fasterxml.jackson.databind.cfg.MapperBuilder.addModule(MapperBuilder.java:243)
kafka-connect-1  |      at com.landoop.json.sql.JacksonJson$.<clinit>(JacksonJson.scala:26)
kafka-connect-1  |      ... 38 more

#####  ELASTIC  6 CONNECTOR

kafka-connect-1  | java.lang.ExceptionInInitializerError
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.Transform$.apply(Transform.scala:97)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticJsonWriter.$anonfun$insert$6(ElasticJsonWriter.scala:122)
kafka-connect-1  |      at scala.collection.immutable.Vector1.map(Vector.scala:1872)
kafka-connect-1  |      at scala.collection.immutable.Vector1.map(Vector.scala:375)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticJsonWriter.$anonfun$insert$5(ElasticJsonWriter.scala:115)
kafka-connect-1  |      at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
kafka-connect-1  |      at scala.collection.mutable.Growable.addAll(Growable.scala:62)
kafka-connect-1  |      at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
kafka-connect-1  |      at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:142)
kafka-connect-1  |      at scala.collection.mutable.ArrayBuffer.addAll(ArrayBuffer.scala:42)
kafka-connect-1  |      at scala.collection.mutable.GrowableBuilder.addAll(GrowableBuilder.scala:34)
kafka-connect-1  |      at scala.collection.mutable.GrowableBuilder.addAll(GrowableBuilder.scala:25)
kafka-connect-1  |      at scala.collection.mutable.Builder$$anon$1.addAll(Builder.scala:81)
kafka-connect-1  |      at scala.collection.mutable.Builder$$anon$1.addAll(Builder.scala:78)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
kafka-connect-1  |      at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticJsonWriter.$anonfun$insert$1(ElasticJsonWriter.scala:109)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
kafka-connect-1  |      at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
kafka-connect-1  |      at scala.collection.immutable.HashMap.flatMap(HashMap.scala:39)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticJsonWriter.insert(ElasticJsonWriter.scala:99)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticJsonWriter.write(ElasticJsonWriter.scala:90)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkTask.$anonfun$put$2(ElasticSinkTask.scala:71)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkTask.$anonfun$put$2$adapted(ElasticSinkTask.scala:71)
kafka-connect-1  |      at scala.Option.foreach(Option.scala:437)
kafka-connect-1  |      at com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkTask.put(ElasticSinkTask.scala:71)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
kafka-connect-1  |      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
kafka-connect-1  |      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-connect-1  |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
kafka-connect-1  |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
kafka-connect-1  |      at java.base/java.lang.Thread.run(Thread.java:829)
kafka-connect-1  | Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.13.3 requires Jackson Databind version >= 2.13.0 and < 2.14.0
kafka-connect-1  |      at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
kafka-connect-1  |      at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
kafka-connect-1  |      at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
kafka-connect-1  |      at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
kafka-connect-1  |      at com.fasterxml.jackson.databind.cfg.MapperBuilder.addModule(MapperBuilder.java:243)
kafka-connect-1  |      at com.landoop.json.sql.JacksonJson$.<clinit>(JacksonJson.scala:26)`

_Originally posted by @jdeex in https://github.com/lensesio/stream-reactor/issues/760#issuecomment-1270388023_

**Comment by davidsloan** [comment]
Thanks for reporting and apologies for the slow reply.  I believe we have the solution for the issue now - would you be willing to help test it out?

**Comment by jdeex** [comment]
> Thanks for reporting and apologies for the slow reply. I believe we have the solution for the issue now - would you be willing to help test it out?

Sure

**Comment by jdeex** [comment]
During connect startup I see the JARs being added, but when I attempt to create a connector it fails saying there is no class available for that connector... class names are ok though

Connect startup log:
`kafka-connect-1  | [2023-02-01 10:59:30,000] INFO Scanning for plugin classes. This might take a moment ... (org.apache.kafka.connect.cli.ConnectDistributed)
kafka-connect-1  | [2023-02-01 10:59:30,019] INFO Loading plugin from: /usr/local/share/kafka/plugins/kafka-connect-elastic6-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,272] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/local/share/kafka/plugins/kafka-connect-elastic6-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'com.datamountaineer.streamreactor.connect.converters.source.JsonResilientConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'lshaded.confluent.connect.avro.AvroConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'org.apache.kafka.connect.json.JsonConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'com.landoop.connect.sql.Transformation' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'org.apache.kafka.connect.connector.policy.AllConnectorClientConfigOverridePolicy' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,273] INFO Added plugin 'org.apache.kafka.connect.connector.policy.PrincipalConnectorClientConfigOverridePolicy' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,274] INFO Added plugin 'org.apache.kafka.connect.connector.policy.NoneConnectorClientConfigOverridePolicy' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:37,294] INFO Loading plugin from: /usr/local/share/kafka/plugins/kafka-connect-elastic7-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:42,009] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/local/share/kafka/plugins/kafka-connect-elastic7-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 10:59:42,009] INFO Added plugin 'com.datamountaineer.streamreactor.connect.elastic7.ElasticSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)`

Connect REST API error while creating the connector:
`"error_code": 500,
    "message": "Failed to find any class that implements Connector and which name matches com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkConnector...`

POST:
`{
    "name": "es-sink-connector",
    "config": {
        "connector.class": "com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkConnector",
        "tasks.max": "1",
        "topics": "es-topic",
        "connect.elastic.protocol": "https",
        "connect.elastic.hosts": "elasticsearch",
        "connect.elastic.port": "9200",
...}`

**Comment by jdeex** [comment]
Elastic6 Seems to be working now, it is delivering messages from several topics. Mind that "types removal" WARN though:

`kafka-connect-1  | [2023-02-01 13:14:14,577] WARN request [POST https://elasticsearch:9200/_bulk?refresh=true] returned 1 warnings: [299 Elasticsearch-7.17.4-79878662c54c886ae89206c685d9f1051a9d6411 "[types removal] Specifying types in bulk requests is deprecated."] (org.elasticsearch.client.RestClient)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [1] records for [flv] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [1] records for [mix] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [2] records for [fa] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [8] records for [ku] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [1] records for [fc] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [1] records for [dvf] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:14,578] INFO Delivered [14] records for [ins] since 2023-02-01 13:03:04 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:14:19,049] INFO Flushing Elastic Sink (com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkTask)`

### Tested using:
Elastic6 connector
Elasticsearch version: 7.17.4
Kafka version: 7.3.1-ccs

`kafka-connect-1  | [2023-02-01 12:50:18,662] INFO Scanning for plugin classes. This might take a moment ... (org.apache.kafka.connect.cli.ConnectDistributed)
kafka-connect-1  | [2023-02-01 12:50:18,682] INFO Loading plugin from: /usr/local/share/kafka/plugins/kafka-connect-elastic6-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 12:50:24,793] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/local/share/kafka/plugins/kafka-connect-elastic6-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 12:50:24,793] INFO Added plugin 'com.datamountaineer.streamreactor.connect.elastic6.ElasticSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 12:50:24,793] INFO Added plugin 'com.datamountaineer.streamreactor.connect.converters.source.JsonResilientConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)`

**Comment by jdeex** [comment]
Elastic7 Seems to be working now, it is delivering messages from several topics:

`kafka-connect-1  | [2023-02-01 13:42:52,857] INFO Flushing Elastic Sink (com.datamountaineer.streamreactor.connect.elastic7.ElasticSinkTask)
kafka-connect-1  | [2023-02-01 13:42:59,743] INFO Delivered [1] records for [flv] since 2023-02-01 13:36:19 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:42:59,743] INFO Delivered [1] records for [mix] since 2023-02-01 13:36:19 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:42:59,743] INFO Delivered [1] records for [fa] since 2023-02-01 13:36:19 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:42:59,743] INFO Delivered [2] records for [fc] since 2023-02-01 13:36:19 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)
kafka-connect-1  | [2023-02-01 13:42:59,743] INFO Delivered [1] records for [dvf] since 2023-02-01 13:36:19 (com.datamountaineer.streamreactor.common.utils.ProgressCounter)`

### Tested using:

Elastic7 connector
Elasticsearch version: 7.17.4
Kafka version: 7.3.1-ccs

`kafka-connect-1  | [2023-02-01 12:50:24,806] INFO Loading plugin from: /usr/local/share/kafka/plugins/kafka-connect-elastic7-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect-1  | [2023-02-01 12:50:29,351] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/local/share/kafka/plugins/kafka-connect-elastic7-kafka-3-3-assembly-4.0.0-22-g45a67a01.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)`

**Comment by davidsloan** [comment]
Confirmed working by @jdeex
