### ISSUE TITLE
s3 sink, how to partition by date formatted from a field value?

### ISSUE THREAD

**Issue by jeacott1** [lensesio/stream-reactor#894]
I'm trying to use the S3SinkConnector, and would very much like to partition the files in s3 by YY-MM derived from a field in my record.
I see there's a _date option (no obvious docs, just a merged PR) but it seems to only consider the record timestamp.
I'd like to be able to use the source timestamp of my data (database in my case), not the arbitrary time it made it into kafka.
is there any means to do this with _value for example? or other option I may have missed?
is there any means to control the s3 object naming too? this seems to be the only connector with no option here.

Thanks in advance.

**Comment by davidsloan** [comment]
Hi there @jeacott1 

> I'm trying to use the S3SinkConnector, and would very much like to partition the files in s3 by YY-MM derived from a field in my record.

Yes this is possible but this doesn't need to be connector functionality as you can do this with a series of Kafka Connect transform.

1. Set up 2 [HeaderFrom transform](https://docs.confluent.io/platform/current/connect/transforms/headerfrom.html#description) to extract the timestamp from the data into headers (one for month, one for year).
2. You can set up the [timestampconverter](https://docs.confluent.io/platform/current/connect/transforms/timestampconverter.html#timestampconverter
) to convert these header values into the "MM" and "DD" respectively.
3. Then use the [connector's header partitioning](https://docs.confluent.io/platform/current/connect/transforms/timestampconverter.html#timestampconverter
).



> is there any means to control the s3 object naming too? this seems to be the only connector with no option here.

Please can you give an example of what you are looking for? We allow [control of the path](https://docs.lenses.io/5.0/integrations/connectors/stream-reactor/sinks/s3sinkconnector/#partitioning-options) via partitioning.

**Comment by davidsloan** [comment]
@jeacott1 please let me know if any further follow up is required.
