### ISSUE TITLE
In MQTT sink connector(kafka-connect-mqtt-1.2.2-2.1.0-all) throw exception Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.13.3 requires Jackson Databind version >= 2.13.0 and < 2.14.0

### ISSUE THREAD

**Issue by rajesh-emagic** [lensesio/stream-reactor#904]

**Comment by davidsloan** [comment]
Thanks for reporting and apologies for the slow reply.  I believe we have the solution for the issue now - would you be willing to help test it out?

**Comment by rajesh-emagic** [comment]
> Thanks for reporting and apologies for the slow reply. I believe we have the solution for the issue now - would you be willing to help test it out?

Hi @davidsloan 
Thanks for your response. But I am still getting issue in sink connector if my kakfa version is above 2.8.2.

**Comment by davidsloan** [comment]
This has now been released - let me know if you are still having a problem.
