### ISSUE TITLE
Source connector - read files from day partition

### ISSUE THREAD

**Issue by iamsamba** [lensesio/stream-reactor#910]
Hi 

I am using s3 source connector 2.8.4 to read parquet files s3 by year, month, day partition.

Connector connected successfully but 0 messages flushed. 

flushing 0 outstanding messages for offset commit

Can someone let me know how do we define connector to flush messages from s3 parquet format by year, month, day partition?

connect.s3.kcql=insert into <topic> select * from <s3 nested folder> PARTITIONBY _date.uuuu,_date.LL,_date.dd  STOREAS `parquet` WITHPARTITIONER=Values
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url= <url>

Thanks,

**Comment by davidsloan** [comment]
@iamsamba can you provide an example of your directory structure on S3?

The source doesn't support the PARTITIONBY keyword but instead uses a Partition Extractor that you define.

Please see the [Partition Extraction section of our documentation](https://docs.lenses.io/5.1/connectors/sources/s3sourceconnector/#partition-extraction) for more details.

**Comment by andrewstevenson** [comment]
@iamsamba are you still having this issue? Did you try the latest release? Please reopen if the issue persists
