### ISSUE TITLE
why do you use RethinkDB

### ISSUE THREAD

**Issue by MaryLilian** [lensesio/stream-reactor#912]
Hi, I am reading your project and I love this project
I have a question, why do you choose RethinkDB in your project instead of other NoSQL like Redis, Cassandra , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose RethinkDB instead of your project instead of other NoSQL like Redis, Cassandra

**Comment by davidsloan** [comment]
I'm not so sure I would consider using RethinkDB for any new project - there are doubts about the future of that particular project since the developers shut it down in 2016.

**Comment by andrewstevenson** [comment]
The company behind RethinkDB shutdown and there was no demand for this connector so we removed it. We support Redis and Cassandra connectors.
