### ISSUE TITLE
Connectors versions are reported incorrectly 

### ISSUE THREAD

**Issue by jeqo** [lensesio/stream-reactor#928]
Kafka Connector plugins report `null` instead of their own (e.g. 4.1.0):

```json
{
  "class": "com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector",
  "type": "source",
  "version": "null"
}
```

See

- https://github.com/aiven/jdbc-connector-for-apache-kafka/blob/bcdf2a24f0b7efeb3a1500999fc04b073329c07d/src/main/java/io/aiven/connect/jdbc/JdbcSinkConnector.java#L75-L78
- https://github.com/aiven/jdbc-connector-for-apache-kafka/blob/bcdf2a24f0b7efeb3a1500999fc04b073329c07d/src/main/java/io/aiven/connect/jdbc/util/Version.java

for an example on how to get version from repository.

**Comment by davidsloan** [comment]
This should be fixed in 
https://github.com/lensesio/stream-reactor/pull/926
and will make it into the next release.

**Comment by jeqo** [comment]
Oh great! Thanks for confirming, will close this one then

**Comment by davidsloan** [comment]
@jeqo thank you for raising it

Please use this, just released:
https://github.com/lensesio/stream-reactor/releases/tag/4.2.0

the versions should be reported correctly now
