### ISSUE TITLE
S3 Source Connector - org.apache.kafka.common.errors.RecordTooLargeException

### ISSUE THREAD

**Issue by IgorTitov012** [lensesio/stream-reactor#935]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?

4.2.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?

Yes, Apache Kafka version 2.8.0

### Have you read the [docs](https://docs.lenses.io/connectors/)?

Yes

### What is the expected behaviour?

Data is restored from s3 bucket to kafka topic using S3SourceConnector

### What was observed?

Some messages recovered, but at some point the connector return an error: `org.apache.kafka.common.errors.RecordTooLargeException`
But in S3 file `topic/2021/12/10/topic(6_539).bytes` has 2.6 KB size. It looks like the problem is in the logic of reading data from s3 on the kafka source connector side.

### What is your connector properties configuration (my-connector.properties)?
```
connector.class=io.lenses.streamreactor.connect.aws.s3.source.S3SourceConnector
connect.s3.kcql=INSERT INTO backup-{TOPIC_NAME} SELECT * from {S3_BUCKET_NAME}:{TOPIC_NAME} BATCH=1 STOREAS Bytes_KeyAndValueWithSizes LIMIT 10
aws.region=eu-central-1
connect.s3.aws.client=AWS
tasks.max=1
topics=backup-topic
connect.s3.aws.region=eu-central-1
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
errors.log.enable=true
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
```

### Please provide full log files (redact and sensitive information)

```
[Worker-06abea4a452d43d0c] [2023-04-25 14:14:19,447] INFO [***|task-0] [***] Reading next file: RemoteS3PathLocation(***,Some(topic),topic/2021/12/10/topic(6_539).bytes) from line -1 (io.lenses.streamreactor.connect.aws.s3.source.reader.ReaderCreator:36)
[Worker-06abea4a452d43d0c] [2023-04-25 14:14:20,023] ERROR [***|task-0] WorkerSourceTask{id=***} failed to send record to transaction:  (org.apache.kafka.connect.runtime.WorkerSourceTask:372)
[Worker-06abea4a452d43d0c] org.apache.kafka.common.errors.RecordTooLargeException: The message is 1623824678 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
```

**Comment by lisolu** [comment]
We are experiencing the same issue with the following **connector configuration**:

```
connect.s3.aws.region=eu-central-1
connector.class=io.lenses.streamreactor.connect.aws.s3.source.S3SourceConnector
connect.s3.kcql=INSERT INTO topic-a SELECT * FROM msk_backup_bucket:msk_backup BATCH=1 STOREAS `Bytes_KeyAndValueWithSizes` LIMIT 10
errors.log.enable=true
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter.schemas.enable=false
schema.enable=false
tasks.max=1
topics=topic-a
```

**Error log**:
```
[Worker-044db231cd5da6609] Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The message is 1654296313 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
```

Changing the limit in KCQL to 1 we experience the OutOfMemory error described in [issue 877](https://github.com/lensesio/stream-reactor/issues/877).

**Comment by stheppi** [comment]
@lisolu / @IgorTitov012 

We recommend taking advantage of the 5.0 release, utilizing the envelope to store both the key, value, and metadata. Please refer to the documentation available [here](https://docs.lenses.io/5.3/connectors/sinks/s3sinkconnector/). This approach mitigates the problems associated with the raw-byte format, eliminating the errors, and enhancing the backup and restore capabilities provided by the sink-source combination.

As the new approach effectively resolves the issue, we will proceed to close it.
