### ISSUE TITLE
S3 Sink support for ignoring tombstones

### ISSUE THREAD

**Issue by dipeti** [lensesio/stream-reactor#938]
Hi, I am using `kafka-connect-aws-s3-assembly-4.2.0` and trying to back up a compacted kafka topic which contains tombstone records. Unfortunately the avro converter throws an exception: 

`2023-05-04 16:21:23,906 ERROR [be-s3-sink-msk-connector|task-0] Encountered error [java.lang.NullPointerException: null of com.dipeti.Snapshots] (io.lenses.streamreactor.connect.aws.s3.sink.S3SinkTask) [task-thread-be-s3-sink-msk-connector-0]
`

I would like to know if there's a possibility to add a configuration property to drive the behaviour of consuming null values (ignore or fail). Similar functionality exists in the confluent-managed [S3 Sink](https://docs.confluent.io/kafka-connectors/s3-sink/current/configuration_options.html), see `behavior.on.null.values`.

**Comment by stheppi** [comment]
@aidan-melen did you get to run the 5.0.1 release?
Keep in mind going forward backing to s3 should leverage the envelope capabilities. See `store.envelope` in the docs [here](https://docs.lenses.io/5.3/connectors/sinks/s3sinkconnector/). The connector is capable of handling tombstone records.

**Comment by stheppi** [comment]
Since version 5.0 the connectors support storing the entire message payload. Please see the documentation [here](https://docs.lenses.io/5.4/connectors/sinks/s3sinkconnector/). This solves the issue of backing up compacted topics.
