### ISSUE TITLE
SSL for Elasticsearch

### ISSUE THREAD

**Issue by arnitolog** [lensesio/stream-reactor#940]
Is it possible to specify SSL options (truststore type/location/password, tls version) for the Elasticsearch connector?
Didn't find anything in the documentation.

**Comment by davidsloan** [comment]
@arnitolog this is not currently supported.

We would love to accept code contributions in this area if you are interested.

There are examples of SSL support in some of our other connectors (eg Cassandra, Redis).

**Comment by andrewstevenson** [comment]
@arnitolog 7.4.5 is release with support for SSL
